### ISSUE TITLE
Discussion: Compilation on Application Thread

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#12494]
There exists code to perform a compilation on an application thread - this means that the java thread will stop running java code, start executing code in the libj9jit dll, compile the method, and then start executing said method. However, this does not happen by default and therefore is highly untested.

I'm opening this issue to discuss whether there is any real benefit to keeping this code around.

**Comment by dsouzai** [comment]
@mpirvu @vijaysun-omr @mstoodle could you provide your opinions on the matter?

**Comment by mpirvu** [comment]
Some time ago I wanted to delete this code, but Mark pointed out something (which I don't remember now) that changed my mind. I believe the code is still exercised in Jartester.

**Comment by dsouzai** [comment]
@mstoodle reminder ping :)

**Comment by mstoodle** [comment]
Marius' recollection is intriguing as I have a dim recollection of that conversation as well. But I haven't been able to come up with a compelling reason to keep it around.

I *believe* it could have been a scenario where you are relying heavily on AOT code and want to do something like our nw extinct AOTRT library, which contained everything needed to load and run AOT compiled code but none of the machinery for compiling code. In that kind of scenario, loading code via the application threads might make sense. One could imagine that fitting an edge computing scenario maybe, but I don't think we should keep it around "just in case" (particularly since it's not well exercised now). We can always resuscitate the appropriate bits for reference if needed in future.
