### ISSUE TITLE
Refactor J9::Options::fePreProcess

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#12504]
`J9::Options::fePreProcess` is ridiculously big; a lot of it can naturally be split up into smaller methods.

**Comment by singh264** [comment]
@dsouzai requesting to work on issue

**Comment by dsouzai** [comment]
Thanks @singh264, assigned this to you.

**Comment by nbhuiyan** [comment]
The progress with the options processing work got stalled a while ago due to infra-related issues. I do not have a timeline for when that work can be contributed at this time, so I do not think any work to improve the existing options processing components should be affected in anticipation of its replacement.
