### ISSUE TITLE
JEP 403: Strongly Encapsulate JDK Internals

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12727]
See https://openjdk.java.net/jeps/403

**Comment by pshipton** [comment]
@tajila @llxia fyi

**Comment by tajila** [comment]
Any place where we added the `--illegal-access=permit` flag in the last release will no longer work.

```
As the next step toward strongly encapsulating all internal elements of the JDK we propose to change the treatment of the permit, warn, and debug modes so that they have no effect, and to issue a warning message to say so.
```

We either need to use newer APIs (ie. Varhandles instead of Unsafe) or add `--add-opens..` options.

**Comment by llxia** [comment]
@LongyuZhang could you help to update tests in openj9 repo? Thanks

**Comment by LongyuZhang** [comment]
- For test [`StaticAccessChecks-IllegalAccessPermit`](https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java9andUp/playlist.xml#L394) and [`StaticAccessChecks-IllegalAccessDeny`](https://github.com/eclipse-openj9/openj9/blob/0af5c29f6cd9a23b9e05ee4715f7a4aad740ae9c/test/functional/Java9andUp/playlist.xml#L418), which two only differ in `--illegal-access`. Since the `permit` value will not work in jdk 17, shall we limit `StaticAccessChecks-IllegalAccessPermit` test versions from original `9+` to only `11 and 16` to exclude `17+`? Thanks.
- Similar for test `cmdLineTester_modularityddrtests`, which has several pairs of tests in xml file with `illegal-access` as `permit` and `deny`, such as [`Run !dumpmodule exports --illegal-access=permit`](https://github.com/eclipse-openj9/openj9/blob/0af5c29f6cd9a23b9e05ee4715f7a4aad740ae9c/test/functional/cmdLineTests/modularityddrtests/modularityddrtests.xml#L568) and [`Run !dumpmodule exports --illegal-access=deny`](https://github.com/eclipse-openj9/openj9/blob/0af5c29f6cd9a23b9e05ee4715f7a4aad740ae9c/test/functional/cmdLineTests/modularityddrtests/modularityddrtests.xml#L585), should these `--illegal-access=permit` ones also be limited to exclude `17+`? Thanks.

**Comment by pshipton** [comment]
> shall we limit StaticAccessChecks-IllegalAccessPermit test versions from original 9+ to only 11 and 16 to exclude 17+

Yes. But also create another variation of StaticAccessChecks-IllegalAccessDeny that runs with `--illegal-access=permit` on jdk17+

> should these --illegal-access=permit ones also be limited to exclude 17+

Yes.

**Comment by LongyuZhang** [comment]
All tests related to JEP 403 have been modified and merged. (Issue https://github.com/eclipse-openj9/openj9/issues/12890 will keep open as a reminder to enable `StaticAccessCheck` test later). 
Thanks for all the help, and I think we can close this issue.

**Comment by pshipton** [comment]
I'll just keep it open a while until we have a build running where we can verify the tests are working.

**Comment by pshipton** [comment]
Builds/tests have been running for some time.
