### ISSUE TITLE
Hotspot threw IncompatibleClassChangeError, while J9 executed normally

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#12992]
### Summary
We modified a test case and executed it with different JVMs. The test result is that hotspot throws an IncompatibleClassChangeError, while J9 executes normally. The simplified test case can be found in the attachment.

We checked the description of IncompatibleClassChangeError in the JVM spec, and the most likely description related to this ISSUE is on page 386.
> During resolution of this symbolic reference, any of the exceptions pertaining to class or interface resolution can be thrown. Otherwise, resolution of H succeeds. 
> 
> If any of the following is true, an IncompatibleClassChangeError is thrown:
> – H is not in the same run-time package as M.
> – H lacks a NestMembers attribute.
> – H has a NestMembers attribute, but there is no entry in its classes array that refers to a class or interface with the name N, where N is the name of M.

http://cr.openjdk.java.net/~iris/se/11/latestSpec/java-se-11-jvms-draft-diffs.pdf

We speculate that it is related to this description because we deleted the following definitions in  the test case. Anyway, this is based on our speculation, hope it helps.
```
InnerClass B=class ICCE$1B;
InnerClass A=class ICCE$1A;
```

### How to reproduce?
[ICCE.zip](https://github.com/eclipse-openj9/openj9/files/6670401/ICCE.zip)
Follow the commands in readme.

### Affected versions
Linux:
```
Ubuntu 18.04.2 LTS
CPU model: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPU cores: two octa-core CPUs
Memory: 96452 MB
```

Java -version output  under Linux
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210421_1000 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
```

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-jenkins_2021_06_12_17_03-b00)
Eclipse OpenJ9 VM (build v0.27.0-release-3309d95fad9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210612_1 (JIT enabled, AOT enabled)
OpenJ9   - 3309d95fad9
OMR      - 4ed9b9de52f
JCL      - b872217a700 based on jdk8u302-b05)
```

```
openjdk version "11.0.12-internal" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxRelease)
Eclipse OpenJ9 VM (build v0.27.0-release-3309d95fad9, JRE 11 Linux amd64-64-Bit Compressed References 20210612_1 (JIT enabled, AOT enabled)
OpenJ9   - 3309d95fad9
OMR      - 4ed9b9de52f
JCL      - a4db72eb0f8 based on jdk-11.0.12+5)
```

macOS:
```
macOS Big Sur
Version 11.2.3 (20D91)
Processor 2.3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
```

Java -version output under macOS
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210421_909 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
```

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-jenkins_2021_06_12_22_18-b00)
Eclipse OpenJ9 VM (build v0.27.0-release-3309d95fad9, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210612_1 (JIT enabled, AOT enabled)
OpenJ9   - 3309d95fad9
OMR      - 4ed9b9de52f
JCL      - b872217a700 based on jdk8u302-b05)
```

```
openjdk version "11.0.12-internal" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12-internal+0-adhoc.jenkins.BuildJDK11x86-64macRelease)
Eclipse OpenJ9 VM (build v0.27.0-release-3309d95fad9, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210612_1 (JIT enabled, AOT enabled)
OpenJ9   - 3309d95fad9
OMR      - 4ed9b9de52f
JCL      - a4db72eb0f8 based on jdk-11.0.12+5)
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by JavaTailor** [comment]
Hi, @tajila 
This issue can be completely reproduced, could you please take a look? :)

**Comment by tajila** [comment]
@ChengJin01 Please take a look at this

**Comment by ChengJin01** [comment]
Hi @JavaTailor,

1) The description of `IncompatibleClassChangeError` I your mentioned at http://cr.openjdk.java.net/~iris/se/11/latestSpec/java-se-11-jvms-draft-diffs.pdf is intended for nested mate introduced in Java11 (JEP 181: Nest-Based Access Control) at https://openjdk.java.net/jeps/181, which is irrelevant to the exception with inner classes as it is also captured in Java 8:
```
$ ../jdk8_hotspot/bin/java  -version
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_302-internal-202105071817-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.302-b01, mixed mode)

$ ../jdk8_hotspot/bin/java  -cp . ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: ICCE and ICCE$1A disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at ICCE.main(ICCE.jasm)
```

2) The exception was triggered & captured by Hotspot after you intentionally deleted the `InnerClasses` attribute in `ICCE` because the inconsistency occurred between the innerclass (`ICCE$1A`) and outer class (`ICCE`) in this attribute.

Technically the exception should be captured even though the behaviour is not identified in the JVM8 Spec. I will need to go through our code involved to see what is missing & what to do to address the situation.

**Comment by JavaTailor** [comment]
Hi @ChengJin01 
Thanks for your reply!
We are glad to provide any help if necessary!

**Comment by ChengJin01** [comment]
1) Looking at the code at https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/Class.java & https://github.com/eclipse-openj9/openj9/blob/master/runtime/jcl/common/java_lang_Class.cpp
```
public Class<?> getDeclaringClass() {
	if (cachedDeclaringClassOffset == -1) {
		cachedDeclaringClassOffset = getFieldOffset("cachedDeclaringClass"); //$NON-NLS-1$
	}
	if (cachedDeclaringClass == null) {
		Class<?> localDeclaringClass = getDeclaringClassImpl(); <---- get the outer class based on the InnerClasses attribute
		if (localDeclaringClass == null) {
			localDeclaringClass = ClassReflectNullPlaceHolder.class;
		}
		writeFieldValue(cachedDeclaringClassOffset, localDeclaringClass);
	}

	/**
	 * ClassReflectNullPlaceHolder.class means the value of cachedDeclaringClass is null
	 * @see ClassReflectNullPlaceHolder.class
	 */
	Class<?> declaringClass = cachedDeclaringClass == ClassReflectNullPlaceHolder.class ? null : cachedDeclaringClass;
	if (declaringClass == null) {  <---- declaring class (the outer class) is null 
		return declaringClass;
	}
....

object JNICALL
Java_java_lang_Class_getDeclaringClassImpl(JNIEnv *env, jobject recv)
{
	J9VMThread *currentThread = (J9VMThread*)env;
	J9JavaVM *vm = currentThread->javaVM;
	J9InternalVMFunctions *vmFuncs = vm->internalVMFunctions;
	j9object_t resultObject = NULL;
	vmFuncs->internalEnterVMFromJNI(currentThread);
	J9Class *clazz = J9VM_J9CLASS_FROM_HEAPCLASS(currentThread, J9_JNI_UNWRAP_REFERENCE(recv));
	J9ROMClass *romClass = clazz->romClass;
J9UTF8 *outerClassName = J9ROMCLASS_OUTERCLASSNAME(romClass); <----- filled in ROMClass based on on the InnerClasses attribute
	if (NULL != outerClassName) {
		J9Class *outerClass = vmFuncs->internalFindClassUTF8(currentThread, J9UTF8_DATA(outerClassName), J9UTF8_LENGTH(outerClassName), clazz->classLoader, J9_FINDCLASS_FLAG_THROW_ON_FAIL);
		resultObject = J9VM_J9CLASS_TO_HEAPCLASS(outerClass);
	}
	jobject result = vmFuncs->j9jni_createLocalRef(env, resultObject);
	vmFuncs->internalExitVMToJNI(currentThread);
	return result;
}
```
It shows whether the outer class is fetched successfully depends on whether the outer class info exists in the `InnerClasses` attribute (filled into the ROMClass when loading class)

2) Looking at the failing classes attached in this issue against the definition of `InnerClasses` in the JVM Spec:
```
InnerClasses_attribute {
 u2 attribute_name_index;
 u4 attribute_length;
 u2 number_of_classes;
 { u2 inner_class_info_index;
 u2 outer_class_info_index;  <-----------
 u2 inner_name_index;
 u2 inner_class_access_flags;
 } classes[number_of_classes];
}

public class ICCE
  minor version: 0
  major version: 52
<--- the InnerClasses attribute was removed in this outer class

class ICCE$1A
  minor version: 0
  major version: 52
...
EnclosingMethod: #16.#17                // ICCE.main
InnerClasses:
  #10= #2;                                // A=class ICCE$1A <--- there is no outer class info
along with the  ICCE$1A.jasm
class ICCE$1A {
  [] { // Constant Pool
    class #19; // #2
    Utf8 "A"; // #10
...
    Attr(#11) { // InnerClasses
      [] { // classes
        #2 (inner_class_info_index ) #0 (outer_class_info_index) #10 (inner_name_index) 0;   
               <----- #0 means the outer class doesn't exist for ICCE$1A
      }
    } // end InnerClasses
...

class ICCE$1B extends ICCE$1A

EnclosingMethod: #16.#17                // ICCE.main
InnerClasses:
  #10= #2;                                // B=class ICCE$1B  <--- there is no outer class info
  #21= #3;                                // A=class ICCE$1A <--- there is no outer class info
...
along with ICCE$1B.jasm
class ICCE$1B {
    Attr(#11) { // InnerClasses
      [] { // classes
        #2 #0 #10 0;  <----- #0 means the outer class doesn't exist for ICCE$1B
        #3 #0 #21 0;  <----- #0 means the outer class doesn't exist for ICCE$1B
      }
    } // end InnerClasses
```

The code logic takes the `InnerClasses` attribute from both the inner class and the outer class into account, which means `IncompatibleClassChangeError` should be captured when an inner class points to the outer class in its `InnerClasses` attribute while the outer class has no `InnerClasses` attribute or doesn't have an entry to the inner class.

With this logic above, apparently there is no way to determine the direct relationship between `ICCE` and ` ICCE$1A` after removing the `InnerClasses` attribute in `ICCE` and the outer class info of the `InnerClasses` attribute in ` ICCE$1A`. 

So I regenerated the `ICCE$1A`.class via `asmtools.jar` by restoring the outer class info of the `InnerClasses` attribute in ` ICCE$1A` 
```
class ICCE$1A
EnclosingMethod: #16.#17                // ICCE.main
InnerClasses:
     #10= #2 of #16; //A=class ICCE$1A of class ICCE  <---- the outer class info for ICCE 

along with the ICCE$1A.jasm
class ICCE$1A {
  [] { // Constant Pool
    class #19; // #2
    class #21; // #16
    Utf8 "A"; // #10
    Utf8 "ICCE"; // #21
...
   Attr(#11) { // InnerClasses
      [] { // classes
        #2 #16 #10 0;    #16 points to the outer class is "ICCE" at #21 in the constant pool
      }
    } // end InnerClasses
```
in which case our build works as expected to throw out `IncompatibleClassChangeError` due to the modified setting in the `InnerClasses` above:
```
$ ../jdk8_openj9_nightly/bin/java -cp . ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: incompatible InnerClasses attribute 
between "ICCE$1A" and "ICCE"
	at java.lang.Class.getDeclaringClass(Class.java:1066)
	at ICCE.main(ICCE.jasm)
```

Based on the investigation above, I don't think there is anything wrong in our existing implementation & logic given the relationship between `ICCE$1A` and `ICCE` is only determined by the `InnerClasses` attribute. I have no idea how `IncompatibleClassChangeError` is triggered on Hotspot without the key outer class data in  the `InnerClasses` attribute of `ICCE$1A` but apparently it is not the reasonable way to do so whatever it comes to if Hotspot relies on something else except the `InnerClasses` attribute, in which case the error message with the `InnerClasses` attribute is misleading.

**Comment by ChengJin01** [comment]
Hi @JavaTailor,

Please add the missing outer class info to the `InnerClasses` attribute of `ICCE$1A` (as I explained above) if you need to verify the inconsistency of this attribute on both the inner class & outer class by triggering `IncompatibleClassChangeError`.  Hotspot might resort to other info to deduce the relationship (e.g. by invoking `getEnclosingClass` to identify `ICCE` but it is for all enclosing classes, which is incorrect for other cases) to trigger the exception which we don't think reasonable given the key outer class info is removed in the `InnerClasses` attribute of `ICCE$1A`.

**Comment by JavaTailor** [comment]
Hi @ChengJin01 
Thanks for your detailed reply! !  :>

Based to your explanation, the inner class *ICCE$1A* lacks the attribute of the outer class, but we did not make any changes to *ICCE$1A*. Then, we  further analyze the test cases. We found that the difference lies in where the inner class is defined. If the inner class is defined inside the function, then no attribute pointing to the outer class will be generated. For example, using the following source code, the *outer_class_info_index* of the generated inner class is #0. 
```
public class ICCE {

    public static void main(String... args) {

        class A {}
        class B extends A {}
        B.class.getSuperclass().getDeclaringClass();
    }
}
```
![2BD1A726-7011-417D-A9B4-8F7EB859ECC2](https://user-images.githubusercontent.com/83168927/124120380-51660980-daa6-11eb-8f9a-919b255a09cf.png)
However, if we define the inner class outside the function, the generated *ICCE$A* will contain the attribute pointing to the outer class.
```
public class ICCE {

    public static void main(String[] args) {

        B.class.getSuperclass().getDeclaringClass();
    }
    class A {}
    class B extends A {}
}
```
![E2B3ED2A-45CF-43AA-804D-8A7A9B69390A](https://user-images.githubusercontent.com/83168927/124120415-59be4480-daa6-11eb-84b4-164e203c2e89.png)

The main difference between these two definitions seems to be the naming of inner classes. If the inner class is defined in the function, the name of the inner class is: ICCE$1A; if the inner class is defined outside the function, the name of the inner class is: ICCE$A. So is it because of the naming that hotspot can distinguish it?  while J9 did not consider this situation?

**Comment by ChengJin01** [comment]
Hi @JavaTailor,

1)  For test 1 in which case both `A` and `B` are defined in the method `main` instead of `ICCE`:
```
public class ICCE {
    public static void main(String... args) {
        class A {}
        class B extends A {}
        B.class.getSuperclass().getDeclaringClass();
    }
}

class ICCE$1A
EnclosingMethod: #11.#12                // ICCE.main
InnerClasses:
     #15= #2; //A=class ICCE$1A

public class ICCE
InnerClasses:
     #7= #2; //B=class ICCE$1B
     #10= #9; //A=class ICCE$1A

```
the `IncompatibleClassChangeError` exception is triggered on Hotspot after removing  the `InnerClasses` attribute in `ICCE`.class
```
$ ../jdk8_hotspot/bin/java ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
ICCE and ICCE$1A disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at ICCE.main(ICCE.java:7)
```

For test 2 in which case both `A` and `B` are defined directly in `ICCE`:
```
public class ICCE {
    public static void main(String[] args) {
        B.class.getSuperclass().getDeclaringClass();
    }
    class A {}
    class B extends A {}
}

class ICCE$A
InnerClasses:
     #17= #3 of #15; //A=class ICCE$A of class ICCE

public class ICCE
InnerClasses:
     #7= #2 of #5; //B=class ICCE$B of class ICCE
     #10= #9 of #5; //A=class ICCE$A of class ICCE
```
the `IncompatibleClassChangeError` exception is triggered on both Hotspot and OpenJ9 after removing  the `InnerClasses` attribute in `ICCE`.class
```
$ ../jdk8_hotspot/bin/java ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
ICCE and ICCE$A disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at ICCE.main(ICCE.java:5)

$ ../jdk8_openj9_nightly/bin/java ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
incompatible InnerClasses attribute between "ICCE$A" and "ICCE"
	at java.lang.Class.getDeclaringClass(Class.java:1066)
	at ICCE.main(ICCE.java:5)
```
The results above indicate an `IncompatibleClassChangeError` exception is triggered on OpenJ9 only when the inconsistency occurs between the actual outer class and its inner classes in terms of the `InnerClasses` attribute, which is logically correct according to the JVM Spec.

3) Looking at the description of `getDeclaringClass` in Class (e.g. at https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaringClass--)
```
public Class<?> getDeclaringClass()
If the class or interface represented by this Class object is a member of another class,
returns the Class object representing the class in which it was declared. 
This method returns null if this class or interface is not a member of any other class.
If this Class object represents an array class, a primitive type, or void,then this method returns null.
```
along with the JVM Spec (e.g. Java 8) at 4.7.6 The `InnerClasses` Attribute says:
```
outer_class_info_index
If C is not a member of a class or an interface (that is, if C is a top-level class or interface (JLS §7.6) or a local class (JLS §14.3) or an anonymous class (JLS §15.9.5)), the value of the outer_class_info_index item must be zero.
Otherwise, the value of the outer_class_info_index item must be a valid index into the constant_pool table, and the entry at that index must be a CONSTANT_Class_info structure representing the class or interface of which C is a member
```
which means:
[1]  `getDeclaringClass` is intended for obtaining the actual outer class of the inner classes if exists.
[2]  the `outer_class_info_index` is 0 when `ICCE$1A` is not a member class of `ICCE` in the original test case (test 1)

That is to say, `getDeclaringClass` should return `null` in test 1 when the `ICCE$1A`'s outer class doesn't exist as indicated in `InnerClasses` attribute of `ICCE$1A`,  whether or not `ICCE` has the `InnerClasses` attribute as `ICCE` is not the outer class of   `ICCE$1A`.  Whether to check the `InnerClasses` attribute of `ICCE` in such case is totally up to the private implementation of JVM which is undefined in the JVM Spec (e.g. determining the enclosing class `ICCE` by invoking `getEnclosingClass()` which is unreasonable)

In addition, deducing the enclosing class or the outer class from the naming of the inner class is technically unreliable/non-standard and might lead to unexpected behaviour, which is out of our consideration unless it is specified in the JVM Spec in the future.

**Comment by ChengJin01** [comment]
@pshipton,  any other input as to test 1 above?

**Comment by JavaTailor** [comment]
Hi, @ChengJin01 
Thanks for your detailed reply! 👍🏻
If you guys confirm this is ok, i am going to close this issue!

**Comment by pshipton** [comment]
The enclosing class doesn't need to be deduced from the name, there is an EnclosingMethod attribute that contains it. The class of the EnclosingMethod  can be used to add the additional check for the InnerClasses attribute and match the Hotspot behavior.

**Comment by ChengJin01** [comment]
Just discussed with @pshipton offline, so we are able to add helper code to check the InnerClass attribute of the Declaring/Enclosing Class to achieve this. I will double-check the code related to see what we can do with this idea.

**Comment by ChengJin01** [comment]
It seems our native code didn't set up correctly to cover the enclosing class with the `InnerClass` attribute in which the outer class index is 0:
```
/runtime/bcutil/ClassFileOracle.cpp
ClassFileOracle::walkAttributes()
{
	ROMClassVerbosePhase v(_context, ClassFileAttributesAnalysis);

	for (U_16 attributeIndex = 0; attributeIndex < _classFile->attributesCount; attributeIndex++) {
		J9CfrAttribute *attrib = _classFile->attributes[attributeIndex];
		switch (attrib->tag) {
		case CFR_ATTRIBUTE_InnerClasses: {
...
				if (outerClassUTF8 == thisClassUTF8) { <--- only intended for the direct outer class
					/* Member class - mark the class' name. */
					markClassNameAsReferenced(entry->innerClassInfoIndex);
					_innerClassCount++;
				} 
```
So all those code including some where in ROMClassWriter need to be modified to deal with the situation.

**Comment by ChengJin01** [comment]
The original test threw out the `IncompatibleClassChangeError` as expected with my changes at https://github.com/ChengJin01/openj9/commit/23de8b77074f2dedd80d8c71e7ccf913fee39d4c
```
$ ../jdk8_openj9_cmk_v1/bin/java ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
incompatible InnerClasses attribute between "ICCE$1A" and "ICCE"
	at java.lang.Class.checkInnerClassAttrOfEnclosingClass(Class.java:1102)
	at java.lang.Class.getDeclaringClass(Class.java:1039)
	at ICCE.main(ICCE.jasm)

$ ../jdk8_hotspot/bin/java  ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
ICCE and ICCE$1A disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at ICCE.main(ICCE.jasm)
```
Will launch internal & open sourced builds to verify the changes.

**Comment by ChengJin01** [comment]
There were a couple of failing test cases in `org/openj9/test/java/lang/Test_Class.java` and internal tests with `java.lang.Class` detected in personal builds which might suggest the fix above is incomplete or some of tests need to updated accordingly to fit with the new changes.

**Comment by ChengJin01** [comment]
It seems that adding the remaining entries of the `InnerClass` attribute to the existing inner classes of the ROM Class doesn't work for two reasons:
1) it is technically impracticable to filter out the expected enclosed inner classes given their outer class could be zero (no outer class at all) or not (the outer class is not the specified declaring class but another class), whether it comes to `getDeclaredClassesImpl` and `isClassADeclaredClass`.
2) the mix of those inner classes in one slot totally messed up the existing logic as the existing slot is only intended for the declared classes, especially in establishing the testing environment with the testng framework in transforming classes.

So the only safe way is to create a separate slot for all remaining enclosed classes in ROM Class to avoid any conflict in the existing code. I will try to prototype this way to see whether it helps to resolve those unexpected test failures.

**Comment by ChengJin01** [comment]
I'd like to double-check what really happened to the failure in the testng framework to understand the root cause in there before moving forward to create a separate slot for these remaining inner class entries.

**Comment by ChengJin01** [comment]
The problem with the failure in the testng framework happens when the `-XX:RecreateClassfileOnload` option is specified to transform ROM classes in which case it is difficult to determine which inner class in the specified ROM Class should be excluded in the newly generated class file based on the mixed inner class entries (only the outer class index is insufficient at this point).

**Comment by ChengJin01** [comment]
I verified the failing test with my latest changes by adding a new field called `enclosedInnerClasses` to ROM Class to store the remaining inner class entries in the `InnerClass` attribute) at https://github.com/ChengJin01/openj9/commit/4e96d0b1288b1ac9bff6150a9b132a99f3fd1366
```
jdk8_openj9_cmk_v3/bin/java -cp   ICCE
Exception in thread "main" java.lang.IncompatibleClassChangeError: 
incompatible InnerClasses attribute between "ICCE$1A" and "ICCE"
	at java.lang.Class.checkInnerClassAttrOfEnclosingClass(Class.java:1104)
	at java.lang.Class.getDeclaringClass(Class.java:1059)
	at ICCE.main(ICCE.jasm)
```
Will double-check in the personal builds to see whether it works good in the existing tests.
