### ISSUE TITLE
DaaLoadTest_daa3_5m_0 failed with OJDK MH enabled

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13132]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly_testList_1/45/
DaaLoadTest_daa3_5m_0
JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly_testList_1/45/system_test_output.tar.gz
```
DLT JUnit Test Results for: net.openj9.test.arithmetics.TestArithmeticOperations
DLT   Ran    : 101
DLT   Passed : 98
DLT   Failed : 3
DLT   Ignored: 0
DLT   Result : FAILED
...
DLT 23:12:34.234 - Test stopped due to reaching runtime limit
DLT 23:12:34.235 - Load test completed
DLT 23:12:34.246 -   Ran     : 2927
DLT 23:12:34.247 -   Passed  : 2919
DLT 23:12:34.247 -   Failed  : 8
DLT 23:12:34.250 -   Result  : FAILED
DLT 23:12:34.257 - Note that only the first 1 failures have been reported
```
The test doesn't show what failed exactly.

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this. We seem to be hitting a timeout, perhaps because of the performance issues.

```
DLT 23:12:34.234 - Test stopped due to reaching runtime limit
```

**Comment by JasonFengJ9** [comment]
Sure, will look into this.

**Comment by JasonFengJ9** [comment]
The result file doesn't have failure details other than the test name `net.openj9.test.arithmetics.TestArithmeticOperations`. There is no core files either.

Regarding `Test stopped due to reaching runtime limit`, I think this is a message to indicate that DaaLoadTest_daa3_**5m**_0 has reached its pre-defined time period `5m`. For example, following output from same test job [1] indicates a PASS
```
23:22:54  DLT 23:22:53.859 - Test stopped due to reaching runtime limit
23:22:54  DLT 23:22:53.860 - Load test completed
23:22:54  DLT 23:22:53.869 -   Ran     : 3273
23:22:54  DLT 23:22:53.870 -   Passed  : 3273
23:22:54  DLT 23:22:53.870 -   Failed  : 0
23:22:54  DLT 23:22:53.872 -   Result  : PASSED
23:22:54  STF 23:22:54.040 - Monitoring Report Summary:
23:22:54  STF 23:22:54.040 -   o Process DLT ended with the expected exit code (0)
23:22:54  STF 23:22:54.041 - EXECUTE stage completed
```

Launched 10x grinder on 5 different machines `Grinder/16877` against an OJDK MH enabled VM (with following -version output) and all passed.
```
12:58:50  openjdk version "16.0.1" 2021-04-20
12:58:50  OpenJDK Runtime Environment Temurin-16.0.1+9 (build 16.0.1+9)
12:58:50  Eclipse OpenJ9 VM Temurin-16.0.1+9 (build master-d5a8afc9d, JRE 16 Linux amd64-64-Bit Compressed References 20210710_61 (JIT enabled, AOT enabled)
12:58:50  OpenJ9   - d5a8afc9d
12:58:50  OMR      - bdee22f4b
12:58:50  JCL      - 3c4bffefe5 based on jdk-16.0.1+9)
```

I think this is a highly intermittent failure, and probably not an OJDK MH specific issue.

[1] https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly_testList_1/45/consoleFull

**Comment by JasonFengJ9** [comment]
From the test history [1], it hasn't appear since its first appearance. In addition, there was no result/diagnosis files. I am leaning towards closing it (and re-open if further analysis is possible).

For now, moving out of release plan.  

[1] https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly/

**Comment by pshipton** [comment]
No new reports, closing.
