### ISSUE TITLE
interface IdentityObject should not be injected into old classes where VT is not supported

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#13339]
interface `IdentityObject` is injected to identity classes by https://github.com/eclipse-openj9/openj9/pull/10282/.

However, I don't see there is a class file version check in that PR. `IdentityObject` should not be injected into old classes where ValueType is not supported.

**Comment by hangshao0** [comment]
FYI @tajila @hzongaro

**Comment by JasonFengJ9** [comment]
Set to release 0.29 tentatively.

**Comment by hzongaro** [comment]
> IdentityObject should not be injected into old classes where ValueType is not supported.

Actually, I think the way things stand in the specification today, old classes can have the `IdentityObject` interface.  According to [section 5.3.5 of the 2021-07-02 updates to the JVM spec](http://cr.openjdk.java.net/~dlsmith/jep401/jep401-20210702/specs/primitive-objects-jvms.html#jvms-5.3.5):

> If either of the following are true, and the interface `IdentityObject` is not already a superinterface of C, C is considered to implement `IdentityObject`.
> - C is an identity class (that is, C is a class that is neither primitive nor abstract)
> - C is an abstract class that declares an instance initializer method, and C does not have its `ACC_PRIM_SUPER` flag set

And according to [section 4.1](http://cr.openjdk.java.net/~dlsmith/jep401/jep401-20210702/specs/primitive-objects-jvms.html#jvms-4.1):

> In a class file with version number 61.65535, the `ACC_PRIM_SUPER` flag indicates that this abstract class may be extended by a primitive class. Primitive instances will be created without executing any instance initialization method of this class (2.9.1). In a class file with any other version number, the 0x0800 bit is ignored, and the `ACC_PRIM_SUPER` flag is considered not to be set.

So I think that means that for older class files, whether an abstract class implements an instance initializer is all that needs to be considered to decide whether the class implements `IdentityObject`, because `ACC_PRIM_SUPER` will not be set, but for newer class files, `ACC_PRIM_SUPER` needs to be considered as well.

**Comment by hangshao0** [comment]
> for older class files, whether an abstract class implements an instance initializer is all that needs to be considered to decide whether the class implements IdentityObject

The is already covered by the current code. 

I did a quick test on RI, I see `getInterfaces()` returns `java.lang.IdentityObject` on an old class file, which is the same as the current OpenJ9 behaviour. 

@hzongaro as you are the person who originally raised this issue, do you see anything else on the old class file ? If no, I think we can close this.

**Comment by hangshao0** [comment]
> that for older class files, whether an abstract class implements an instance initializer is all that needs to be considered to decide whether the class implements IdentityObject

**Comment by hangshao0** [comment]
> that for older class files, whether an abstract class implements an instance initializer is all that needs to be considered to decide whether the class implements IdentityObject

This is already covered by the current code. 

I did a quick test on RI, I see `getInterfaces()` returns `java.lang.IdentityObject` on an old class file.
