### ISSUE TITLE
Multiple test failures with JITServer and Java17

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13421]
After PR #12341 has been merged, many JITServer tests have started failing/crashing with Java17.
Here's a list:
```
cmdLineTester_jvmtitests_7
cmdLineTester_jvmtitests_8
cmdLineTester_jvmtitests_debug_8
cmdLineTester_jvmtitests_debug_10
cmdLineTester_jvmtitests_debug_openj9_none_SCC_3
cmdLineTester_jvmtitests_debug_openj9_none_SCC_5
cmdLineTester_jvmtitests_debug_openj9_none_SCC_11
jit_jitt_array_3
jit_jitt_array_5
JCL_Test_JITHelpers_1
CondyPrimitive_3
cmdLineTester_jvmtitests_5
cmdLineTester_jvmtitests_debug_3
cmdLineTester_jvmtitests_debug_5
cmdLineTester_jvmtitests_debug_7
cmdLineTester_jvmtitests_debug_11
cmdLineTester_jvmtitests_debug_openj9_none_SCC_7
cmdLineTester_jvmtitests_debug_openj9_none_SCC_8
cmdLineTester_jvmtitests_debug_openj9_none_SCC_10
cmdLineTester_decompilationTests_0
cmdLineTester_decompilationTests_1
cmdLineTester_jython_6
CondyPrimitive_2
JCL_Test_JITHelpers_0
jit_jitt_array_0
jit_jitt_array_2
jit_jitt_array_4
jit_jitt_array_6
``` 
Initial scan of the PR mentioned above showed that we need JITServer support for `javaVM->vmtargetOffset` (which is covered by PR #13420).
However, this did not fix the test failures.

**Comment by dmitry-ten** [comment]
So far, I narrowed down the failures to `J9::RecognizedCallTransformer::process_java_lang_invoke_MethodHandle_invokeBasic`.
If the call to this transformer routine is disabled, the failures go away. However, I do not see any problems with the function other than using `vm->vmtargetOffset`fixing which doesn't solve the problem.

I'm currently trying to determine which call from the compiled code leads to the crash.
The crash itself is caused by an invalid cp index passed to `resolveClassRef` during a `jitResolveField` call

**Comment by mpirvu** [comment]
#13425 solved this issue
