### ISSUE TITLE
InternalError: SIGBUS on aarch64 instead of NPE

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13556]
First time we've had aarch64 testing in the open nightly. I expect this should be a NPE and not `InternalError: SIGBUS`

See https://github.com/eclipse-openj9/openj9/issues/13472

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly/1 - cent8-aarch64-1
jdk_lang_1
-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops
java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java
```
01:23:17  test DefaultStaticInvokeTest.testMethodHandleInvoke("TestClass7", "TestIF7.TestClass7"): failure
01:23:17  java.lang.InternalError: SIGBUS
01:23:17  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
01:23:17  	at java.lang.invoke.LambdaForm$MH/0x0000000018793a20.invoke(LambdaForm$MH)
01:23:17  	at java.lang.invoke.LambdaForm$MH/0x0000000018793470.invoke_MT(LambdaForm$MH)
01:23:17  	at DefaultStaticInvokeTest.testMethodHandleInvoke(DefaultStaticInvokeTest.java:169)
```

**Comment by pshipton** [comment]
@knn-k @0xdaryl fyi

**Comment by pshipton** [comment]
Seems we had https://github.com/eclipse-openj9/openj9/issues/13508 open which is closed as a dup. Will that address the SIGBUS problem?

**Comment by jdmpapin** [comment]
The problem in #13472 just has us loading from an address of the form `clazz + sizeof (J9Class) - x` where `x` has its top bit set. I see no reason why (depending on circumstances) this bad load couldn't trap with `SIGBUS` instead of `SIGSEGV`, so I expect that this is a duplicate. #13472 also encompasses outright crashes in cases where the signal was not translated into an exception.
