### ISSUE TITLE
Improve implementation of Reference.refersTo()

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#13659]
The current implementations (both regular and FAST_JNI) of `java.lang.ref.Reference.refersTo()` use `j9gc_objaccess_referenceGet()` which delegates to `referenceGet()` for the relevant GC barrier.

In the case of `MM_RealtimeAccessBarrier`, this ensures the referent is marked which may alter its reachability (needlessly).

Ideally, this could be simplified to a use of `J9VMJAVALANGREFREFERENCE_REFERENT_VM()` for comparison with the given target object reference.

If appropriate, this change should apply to both the regular and FAST_JNI implementations and to code generated by the JIT compiler.

**Comment by amicic** [comment]
The motivation is clear: in case that the target object (passed as argument to refersTo) is not equal to the referent, if in a middle of a cycle, with old behavior we would needlessly mark the referent (while potentially the reference object could have been cleared, and referent collected). Removing the part of the logic that marks the objects is correct.

There is a bit of non-trivial aspect of _unmarkedImpliesCleared flag to consider. The question is if removing also that part of logic would change the behavior, since the old logic could return NULL (at the final phases of a cycle) and make refersTo to return false, while the new logic would compare the object of interest with the current referent object and potentially return true.
But if they are really equal (so that true is returned), we would not have returned NULL in the original logic to start with.
If they are different, they would still return false (same as before, it's just that we previously compared with NULL, and now with the current, but different, referent object). So, even this part of the logic is not necessary.

Overall, the simplification seems correct to me.

**Comment by keithc-ca** [comment]
Thanks, @amicic.
