### ISSUE TITLE
Something wrong with UNB machines

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13966]
See the failures
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK8/173/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/155/
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17/92/
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_ppc64le_linux_OpenJDK/155/console

There are timeouts and failures to contact machines.

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Updates
Nov 23:
- Temporarily increase copyArtifact timeout from 1 to 2 hours in the test builds. Hopefully this allows builds to proceed even if at a snails pace.
- UNB CAS admins escalate to UNB/FCS

Nov 24:
- UNB escalates to Canarie. It seems to be an issue at Seattle. (No ticket number provided to us).

Nov 25:
- No updates

Nov 26:
- Reached out to OSU to see if they can push from their end since the problem is closer to their site physically

**Comment by pshipton** [comment]
Although the download problem is fixed, as per the timeout in https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/38/console there seems to be an upload problem.
```
16:19:58  [consumer_0] Deploying artifact: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder_iteration_0/38/openjdk_test_output.tar.gz
22:21:28  Error occurred for request PUT /artifactory/ci-openj9/Test/Grinder_iteration_0/38/openjdk_test_output.tar.gz;build.parentNumber=413;build.parentName=Grinder;build.timestamp=1638298747762;build.name=Grinder_iteration_0;build.number=38 HTTP/1.1. Received status code 504 and message: Gateway Time-out.
22:21:28  Attempting retry #1
Cancelling nested steps due to timeout
```

**Comment by AdamBrousseau** [comment]
I'm thinking that was a blip or a one off. I see lots of other builds passing. If it happens again let me know.

**Comment by pshipton** [comment]
There is another one happening now but I checked the size and it's a 4GB file, which likely explains why it times out. I'm going to stop the job and transfer just what I need manually.
