### ISSUE TITLE
Timing issue exposed in HookedByTheJit.cpp

### ISSUE THREAD

**Issue by jjohnst-us** [eclipse-openj9/openj9#14004]
We are seeing a random but rare GPF in HookedByTheJit.cpp.
Specifically I believe the issue is here:
https://github.ibm.com/runtimes/openj9/blob/4480d81bba0e0e55d90b017ab8944ca7fceae0af/runtime/compiler/control/HookedByTheJit.cpp#L455

More specifically, during JVM shutdown, there is a timing hole where 
TR_J9VMBase::get(jitConfig, vmThread, TR_J9VMBase::AOT_VM)->sharedCache()
can resolve to zero causing the subsequent deference to access the member function address to fail.

I'm guessing the ultimate solution is to not free that sharedCache structure until the last possible use of it doesn't exist.
Maybe a quick fix/hack would be to check if its zero and take the conditional?

Some assembler instructions showing the offset at the point of failure (offset 3976):
10630                  .LVL1054:
 10631                  .LBB5041:
 10632                  .LBB5042:
 10633                  # /ztpf/java/bld/jvm/official/bld_469669/temp/bld_linux_ztpf_390-64/compiler/../compiler/env/VMJ9.h
1083:/ztpf/java/bld/jvm/official/bld_469669/temp/bld_linux_ztpf_390-64/compiler/../compiler/env/VMJ9.h ****    virtual void              freeSharedCache();
 10634                          .loc 5 1083 0
 10635 3952 E3102060            lg      %r1,96(%r2)     # _192, _190->_sharedCache
 10635      0004
 10636                  .LVL1055:
 10637                  .L963:
 10638                  .LBE5042:
 10639                  .LBE5041:
 10640                  # /ztpf/java/bld/jvm/official/bld_469669/temp/bld_linux_ztpf_390-64/compiler/../compiler/control/Ho
 462:/ztpf/java/bld/jvm/official/bld_469669/temp/bld_linux_ztpf_390-64/compiler/../compiler/control/HookedByTheJit.cpp ****             {
 10641                          .loc 10 462 0
 10642 3958 E3309008            lg      %r3,8(%r9)      # tmp710, method_154->constantPool
 10642      0004
 10643 395e A537FFF0            nill    %r3,65520       # tmp477,
 10644 3962 B9040021            lgr     %r2,%r1 #, _192
 10645 3966 E3101000            lg      %r1,0(%r1)      # _192->D.187559._vptr.TR_SharedCache, _192->D.187559._vptr.TR_SharedCache
 10645      0004
 10646 396c A7490000            lghi    %r4,0   #,
 10647 3970 E3303000            lg      %r3,0(%r3)      # _38->ramClass, _38->ramClass
 10647      0004
 **10648 3976 E3101060            lg      %r1,96(%r1)     # MEM[(int (*__vtbl_ptr_type) () *)_33 + 96B], MEM[(int (*__vtbl_ptr_type) () *)_33**     failure occurs on this line
 10648      0004
 10649 397c E3303008            lg      %r3,8(%r3)      #, _39->romClass
 10649      0004
 10650 3982 0DE1                basr    %r14,%r1        #, MEM[(int (*__vtbl_ptr_type) () *)_33 + 96B]

Some of the Registers at time of failure (notice R2 is zero).  Also note R1 contains the dereference of zero for our system you allowed to de-reference zero (just not write to it).
*GENERAL REGISTERS                                                     
  R0  0000000B 09595420  000CC000 01018468  R1    R2  00000000 00000000
  R4  00000000 00000000  00000000 00000008  R5    R6  00000000 9DDB0D78
  R8  00000004 802F1598  00000004 8305CB20  R9    R10 00000005 4EA001B0
  R12 00000000 00000000  00000004 830452A4  R13   R14 00000000 9D5A5A60

Thanks, hopefully its obvious based on the information provided above.

**Comment by pshipton** [comment]
@dsouzai @0xdaryl pls find the best person to take a look at this problem affecting z/TPF.

**Comment by dsouzai** [comment]
There's actually a `TR_J9SharedCache` object created for each new FE, and there's an FE created for each `J9VMThread` when  `TRJ9VMBase::get(` is invoked, which happens here:
https://github.com/eclipse-openj9/openj9/blob/73bf9f0ae9bc80572912254116e4b8af70c7af21/runtime/compiler/env/VMJ9.cpp#L662-L688
There's no way to know whether the FE is also NULL, because `r2` got overwritten. I can only imagine it must not be because the constructor didn't crash. However, `_shareCache` could only be NULL if we failed to allocate persistent memory, which _may_ be possible during shutdown, though I can't immediately see how. I also don't think it's use the global `aotVMWithoutThreadInfo` because that only gets set to NULL when freeing the JITConfig which must not be happening yet because we're in `jitHookInitializeSendTarget`. Also, `vmThread->aotVMwithThreadInfo` must be NULL and this is the first time we're allocating something there because otherwise the SCC wouldn't be NULL either.

So maybe all we can do at this point is check whether the FE and _shareCache objects are NULL.
