### ISSUE TITLE
JEP 419 Foreign Function & Memory API (Second Incubator)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14036]
See https://openjdk.java.net/jeps/419

@tajila @ChengJin01

**Comment by ChengJin01** [comment]
I have been working on this new changes as it blocks the Java 18 build with PR on the API changes of Second Incubator at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/379.  It turns out at least the following code related need to updated according to the document and internal implementation in Java 18.
1) the downcall address changes from `Addressaable` to `NativeSymbol` (downcalll APIs modified accordingly)
2) the new function descriptor without TypeKind (replaced by carrier which is the type class)
3) the `boolean` layout is `JAVA_BOOLEAN` (1 byte /officially declared since Java 18 (Second Incubator))
4) how to access data in the native memory (different from Java 17 / a bunch of changes in MemoryAddress, MemorySegment and SegmentAllocator, etc) 

The first step is to ensure the existing code in phase 1 (primitive support / already merged to the repo) works with both Java 17 and 18 given there is no compatibility between them in terms of these changes listed above. And the further update will be covered via the PR (phase 2 & 3: struct support) at https://github.com/eclipse-openj9/openj9/pull/13315.
