### ISSUE TITLE
Questions concerned with Java Modules

### ISSUE THREAD

**Issue by Annette0127** [eclipse-openj9/openj9#14209]
Hi! I am Yirui, a student from Southern University of Science and Technology, and I'm working with professor Joshua Garcia at the University of California, Irvine. We are now doing research related to Java modules from the Java Platform Module System. While looking for existing modularized projects on GitHub, we noticed that, in your project “eclipse-openj9/openj9”, code is partially modularized, which means some folders contain Java modules  (e.g., `openj9.dataaccess` module in the `jcl` folder) while some parts are not (e.g., `java.base` in the `jcl` folder and all the code in the `debugtools` folder). The modules are defined in a module descriptor file named “module-info.java”. If possible, we would like to know the reason for such a design, i.e., how you chose to modularize some parts of your project but not others.

Thank you very much for your valuable time and consideration!

**Comment by pshipton** [comment]
The project supports both Java 8 without modules, and also Java 11+ with modules. Basically we had all the legacy code in `debugtools` and couldn't be bothered to move it all around. It does end up in the openj9.dtfj module in Java 11+ builds. Not sure why you say the code in `java.base` is not modularized. `java.base` is one of the modules. The classes in there replace and augment classes in the OpenJDK `java.base` module in order to support OpenJ9.

**Comment by pshipton** [comment]
In case you don't know, OpenJ9 is an alternative to Hotspot, i.e. instead of OpenJDK with Hotspot, you can have a build of OpenJDK without Hotspot but with OpenJ9 instead. https://www.eclipse.org/openj9/

**Comment by Annette0127** [comment]
Thank you very much for your answer, it is really helpful! 😊
I am sorry about the confusion since I did not realize classes in the `java.base` folder are replacements or augmentations for `java.base` in OpenJDK.
