### ISSUE TITLE
aqa-tests failing to clone on aix71-p8-1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14203]
Disabled the machine.

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly_testList_0/178/
```
The recommended git tool is: git
No credentials specified
Cloning the remote Git repository
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly_testList_0/aqa-tests
```

@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
This happened many many times in the builds last night, although I just showed one example.

**Comment by pshipton** [comment]
Builds fail as well as tests.

https://openj9-jenkins.osuosl.org/job/Build_JDK17_ppc64_aix_Nightly/124
```
21:21:05  The recommended git tool is: NONE
21:21:26  No credentials specified
21:21:26  Cloning the remote Git repository
21:21:27  Cloning repository https://github.com/ibmruntimes/openj9-openjdk-jdk17.git
21:21:27   > git init /home/jenkins/workspace/Build_JDK17_ppc64_aix_Nightly # timeout=10
21:21:27  ERROR: Error cloning remote repo 'origin'
21:21:27  hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Build_JDK17_ppc64_aix_Nightly
```

**Comment by jdekonin** [comment]
I sort of fixed the git issue, but then other packages updated via yum start being a problem.  This is likely because the latest yum packages are verified against the latest AIX oslevels.  I've removed the labels from the machine in the event jenkins restarts and it re-enables magically.  I don't see getting this system updated since we are suppose to be replacing with OSU AIX systems.

I think remaining problem with the OSU system is covered under #14193.

**Comment by pshipton** [comment]
aix71-p8-1 no longer exists.
