### ISSUE TITLE
Compiling with gcc 10.3 hangs/crashes with JIT when running -version

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14219]
It's under discussion to move compilation of jdk17+ to use gcc 10.3 
https://github.com/adoptium/temurin-build/issues/2787

@keithc-ca tried a manual build with 10.3 and found that the build hangs in the `Optimizing the exploded image` step. The problem can also be seen running `java -version`. However running `java -Xint -version` completes without hanging.

@AdamBrousseau @0xdaryl fyi

**Comment by keithc-ca** [comment]
Adding `-Xint` in these definitions in `spec.gmk` allows `make images` to complete.
```
JLINK_CMD := $(JDK_OUTPUTDIR)/bin/jlink -J-Xint
JMOD_CMD := $(JDK_OUTPUTDIR)/bin/jmod -J-Xint
BUILD_JAVA_FLAGS := -Xms64M -Xmx1600M -Xint
```

**Comment by pshipton** [comment]
vmState [0x5ff06]: {J9VMSTATE_JIT} {RegisterAssigning}

**Comment by keithc-ca** [comment]
I think a root cause is the definition of `RegisterDependencyGroup`. It defines an array of 1 `RegisterDependency`, but allocates space for more in the `new` operator.

The optimizer in gcc-10 seems to prioritize the declared array size over `numberOfRegisters` provided in several methods. In particular, it appears that the `for` loops in places like `unblockRegisters()` it doesn't even increment the index (no legal reference could be anything but zero) and so the loop does not terminate.

I tried making the array 'flexible' by declaring its length to be zero, only to find that the class is inherited (e.g. on X in `compiler/x/codegen/OMRRegisterDependency.hpp`) and extended with additional fields (a flexible array member must always be last).

My main question is this (also posted to omr#general slack channel): How did this ever work? The additional fields have offsets beginning in the same place as the second register dependency.

**Comment by keithc-ca** [comment]
With the changes in https://github.com/keithc-ca/omr/tree/gcc10, jdk17 builds with gcc-10 on P, X and Z.
