### ISSUE TITLE
Memory footprint problem while use balanced gc

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#14497]
Java -version output
--------------------

```
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc.jenkins.buildjdk17x86-64windowsnightly)
Eclipse OpenJ9 VM (build master-c462b8b9d0c, JRE 17 Windows 7 amd64-64-Bit Compressed References 20220211_161 (JIT enabled, AOT enabled)
OpenJ9   - c462b8b9d0c
OMR      - e6d7abf
JCL      - 32e63c50bc0 based on jdk-17.0.3+1)
```

Summary of problem
------------------
Use Jconsole to monitor memory footprint of minecraft server. I found that memory footprint is strange. Memory pool "Balanced-old" occupied 415MB memory and balanced-survivor occupied 4MB memory. But minimum heap memory footprint bigger than these pool`s sum. Use full gc can slove these problem.

Diagnostic files
----------------
GC log:
[verbosegc.20220212.232240.136652.zip](https://github.com/eclipse-openj9/openj9/files/8054034/verbosegc.20220212.232240.136652.zip)
Jconsole screenshot:
![G120220212231924862](https://user-images.githubusercontent.com/40121560/153720355-3ca1b665-9427-4d9c-bb9a-82fb3a2089bb.jpg)
![G320220212232014366](https://user-images.githubusercontent.com/40121560/153720363-a795899b-f9b9-4282-92cf-ff36d6ba4a21.jpg)
![G220220212231950758](https://user-images.githubusercontent.com/40121560/153720425-b4204add-6a31-4f2a-a365-90aaa7f3709a.jpg)
![G420220212232035612](https://user-images.githubusercontent.com/40121560/153720442-6c62a9ca-dad6-477e-9587-7e89b6bb6d24.jpg)

**Comment by pshipton** [comment]
@amicic @dmitripivkine

**Comment by LinHu2016** [comment]
Hi @1a2s3d4f1, I am trying to understand your issue here, for balanced GC policy(region base), there are four heap memory-pools (balanced-reserved, balanced-eden, balanced-survivor, balanced-old) in general, balanced-reserved memory pool is the pool that hold the free regions, which have not been assigned to eden, survivor and old( those free regions could be used as eden, survivor and old in future), ideally committed heap size equal to sum of committed sizes of all heap memory pools, but so far I know that jconsole use individual Mxbean API call for retrieving memory usages for each of memory pool, and GC could happens between calls, GC likely changes committed size of memory pools, even expends or contracts heap size, so there is no guaranteed that heap size = sum of the size of all heap memory pools.
If you want to retrieve consistent  heap snapshot, you could use GarbageCollectionNotificationInfo or GarbageCollectorMXBean.getLastGcInfo().
I am not sure if you expect that the committed heap size equal to sum of committed sizes of all heap memory pool here, please let me know if I missed something or misunderstand the issue, Thanks

**Comment by 1a2s3d4f1** [comment]
@LinHu2016 I mean, partial gc contract memory pool(balanced-old). But heap size not be contracted. It could be contracted by Global gc. Use website gceasy.io to analyze gc log. It show old generation size. The old generation size look bigger than memory pool "balanced-old".
![20220216224258877](https://user-images.githubusercontent.com/40121560/154295950-01d624d4-f70d-4e5b-9af9-4f89e22d4e23.jpg)
![20220216224215852](https://user-images.githubusercontent.com/40121560/154296004-1baaa3f1-170e-4c79-baa6-9ea63c199a24.jpg)

[log report](https://gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMjIvMDIvMTYvLS12ZXJib3NlZ2MuMjAyMjAyMTYuMjIzMDMzLjIzNjAuemlwLS0xNC00NS03&channel=WEB)

**Comment by LinHu2016** [comment]
Thanks @1a2s3d4f1 for the detail explanation, `Partial gc contract memory pool(balanced-old). But heap size not be contracted. ` is possible, PGC could pick up a couple tenure regions for part of collection set, in that case, after the collection(PGC) tenure size might be contracted (depends on how many survivor regions has been promoted and how many tenure(old) region has been collected).

**Comment by 1a2s3d4f1** [comment]
@LinHu2016 Thank your anwser. So It have not any issue with balanced gc. It just a logic of gc.
