### ISSUE TITLE
Invalid error message printed at JITServer start with custom number of threads

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [eclipse-openj9/openj9#15397]
If the number of JITServer compilation threads is customized using the `-XcompilationThreads<N>` option, an invalid error message is printed to `stderr` when JITServer starts:
```
Requested number of compilation threads is over the limit of 15. Will use 15 threads.
```
However, the number of threads is set correctly.

It looks like the `-XcompilationThreads` option is first parsed before JITServer options are parsed, which results in the option being rejected because the number of threads is larger than the JIT client limit (15), and later parsed again and handled correctly.

**Comment by cjjdespres** [comment]
I can't seem to observe this. If I run, say, `jitserver -XcompilationThreads7` (or any number between 0 and 15) the server starts up as normal with no error message. Setting it to an invalid number (say 16) causes that message to be printed as expected. Were there particular circumstances in which this happened, or has this been fixed in the meantime?

**Comment by AlexeyKhrabrov** [comment]
The server can have a practically unlimited number of threads, technically up to 999 because only up to 3 digits are parsed. See #12926. I guess the documentation also needs to be updated.

**Comment by AlexeyKhrabrov** [comment]
Opened a doc issue: https://github.com/eclipse-openj9/openj9-docs/issues/966.

**Comment by mpirvu** [comment]
First time we execute `updateNumUsableCompThreads()` we do it from `fepreProcessCompilationThreads()`.
At that point we haven't set the correct information in `getPersistentInfo()->getRemoteCompilationMode()` so we think we are in client mode and look at the limits for the client.
We could use `     if (vm->internalVMFunctions->isJITServerEnabled(vm))` as a test for server mode.

**Comment by mpirvu** [comment]
@cjjdespres Could you please open a PR for this issue? I think the solution could be as simple as using the `vm->internalVMFunctions->isJITServerEnabled(vm)` query instead of `getPersistentInfo()->getRemoteCompilationMode()` in ` TR::CompilationInfo::updateNumUsableCompThreads(int32_t &numUsableCompThreads)`
CompilationInfo caches jitConfig IIRC and from there you can get to J9JavaVM.

**Comment by cjjdespres** [comment]
That fix does work, though now the correct message

```
Requested number of compilation threads is over the limit of 999.
Will use the default number of threads: 63.
```

is printed twice in the log, presumably because `updateNumUsableCompThreads` is called in a few different places.

**Comment by mpirvu** [comment]
Just a guess: We may be processing the AOT options and then the JIT options
