### ISSUE TITLE
CRIU java_lang_System_nanoTime doesn't invoke j9time_nano_time and miss NANO_TIME_ADJUSTMENT w/ -Xjit:count=0

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15513]
`java.lang.System.nanoTime()` invokes `inlSystemNanoTime()` or `Fast_java_lang_System_nanoTime()`, then call `j9time_nano_time()` w/ `NANO_TIME_ADJUSTMENT` which is zero before checkpoint, and set to `privatePortLibrary->nanoTimeMonotonicClockDelta` after restore.

When running w/ a command line option `-Xjit:count=0` before checkpoint, neither `inlSystemNanoTime()` or `Fast_java_lang_System_nanoTime()` is invoked hence no `NANO_TIME_ADJUSTMENT` to `j9time_nano_time()`. It appears `java_lang_System_nanoTime()` is a JIT recognized method, and a JIT version replaced VM natives.

A simple testcase is to run `java.lang.System.nanoTime()` before checkpoint and after restore with different command line options.

FYI @tajila @vijaysun-omr

**Comment by ymanton** [comment]
It looks like we have 3 different ways of generating code for calls to `System.nanoTime()` in the compiler:

1. No special treatment, generate a regular call.
2. Codegen sets the `SupportsCurrentTimeMaxPrecision` flag, Simplifier replaces `System.nanoTime()` call with a sequence containing a call to a "non-helper" called `currentTimeMaxPrecision`, codegen later replaces the call with a suitable implementation. This is currently only used by Z (Linux & ZOS) and the implementation looks like it reads some special memory locations containing time values in some unit.
3. Frontend returns true for `supportsFastNanoTime()`, codegen replaces the call with a suitable implementation. Currently only used by X Linux, implementation is to call `clock_gettime()` directly to read the standard `CLOCK_MONOTONIC`, which is essentially what the JVM implementation of `System.nanoTime()` does once it calls `j9time_nano_time()`. Directly calling `clock_gettime()` basically reduces path length.

As far as the changes needed to support checkpointing go:

1. Currently works as-is and needs no changes.
2. Can be fixed by performing the same adjustment as was done for `j9time_nano_time()` (i.e. subtracting `nanoTimeMonotonicClockDelta`).
3. Would need it's own separate delta value to be captured/calculated and used in the adjustment, since that clock source is (I assume) not guaranteed to be in the same units as `CLOCK_MONOTONIC` (FYI @joransiu @r30shah).

**Comment by vijaysun-omr** [comment]
Let us implement 2 since this is the case that is relevant in the short term (e.g. for beta)
