### ISSUE TITLE
jdk19 Jep425Tests_testVirtualThread test_VirtualthreadYieldResume Virtual Thread 1: incorrect result of 1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15651]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_x86-64_windows_OpenJDK19_testList_1/9
Jep425Tests_testVirtualThread_0
```
13:17:15  FAILED: test_VirtualthreadYieldResume
13:17:15  java.lang.AssertionError: Virtual Thread 1: incorrect result of 1
13:17:15  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
13:17:15  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
13:17:15  	at org.openj9.test.jep425.VirtualThreadTests.test_VirtualthreadYieldResume(VirtualThreadTests.java:86)
```

@tajila fyi

**Comment by tajila** [comment]
@JasonFengJ9 We'll need t exclude these as well

**Comment by babsingh** [comment]
Removing the `test excluded` label since this issue has been resolved.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_Nightly_testList_1/89
Jep425Tests_testVirtualThread_2 `--enable-preview -Xgcpolicy:balanced`
```
01:17:03  FAILED: test_VirtualthreadYieldResume
01:17:03  java.lang.AssertionError: Virtual Thread 0: incorrect result of 2
01:17:03  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
01:17:03  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
01:17:03  	at org.openj9.test.jep425.VirtualThreadTests.test_VirtualthreadYieldResume(VirtualThreadTests.java:87)
```

**Comment by tajila** [comment]
@babsingh can you please take a look at this?

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/15651#issuecomment-1379166505:

### Unable to reproduce the failure

Ran two grinders:
- 100x (20x on 5 different AIX machines): https://openj9-jenkins.osuosl.org/job/Grinder/1827/; and
- 300x (on the AIX machine where the recent failure was seen): https://openj9-jenkins.osuosl.org/job/Grinder/1828/.

The failure couldn't be reproduced.

### Failing test's source code
https://github.com/eclipse-openj9/openj9/blob/b975e8202c2d9d7b709bff8b9140cd98c836f5a3/test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java#L72-L92

### Probable cause

I believe that the problem lies in the below line of the test's source code:
```
executor.awaitTermination(5L, TimeUnit.SECONDS);
```
5 seconds is not sufficient in the worst case scenario.

Why? 6 virtual threads are being launched in the test-case. Each virtual thread sleeps twice for 1 second (2 seconds in total) and performs three arithmetic operations. In addition, there is cost associated to schedule, sleep and wake the thread. Assumption: each virtual thread may take 3-4 seconds to execute in the worst case scenario. If the machine has scarce resources i.e. each virtual thread is executed sequentially (worst-case), the test-case may take `4 seconds x 6 threads = 24 seconds` to execute. Overall, `awaitTermination` should wait for 24 seconds or preferably more for the virtual threads to finish.

**Comment by pshipton** [comment]
Removing from milestone plan since this won't block the release.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_Nightly_testList_1/109
Jep425Tests_testVirtualThread_1
```
02:10:08  FAILED: test_YieldedVirtualThreadGetStackTrace
02:10:08  java.lang.AssertionError: Expected 11 frames, got 7
02:10:08  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
02:10:08  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
02:10:08  	at org.openj9.test.jep425.VirtualThreadTests.test_YieldedVirtualThreadGetStackTrace(VirtualThreadTests.java:182)
```

**Comment by babsingh** [comment]
@fengxue-IS A similar failure from https://github.com/eclipse-openj9/openj9/pull/16693 is seen above. Can you review the test case for other weaknesses?

**Comment by babsingh** [comment]
This issue only tracks failures related to `test_VirtualthreadYieldResume`. The `test_YieldedVirtualThreadGetStackTrace` failure is seen for the first time. @pshipton Should we track it in a new issue?

**Comment by pshipton** [comment]
Yes, sorry. Created https://github.com/eclipse-openj9/openj9/issues/16722
