### ISSUE TITLE
Test Smell: a confusing code organization between production code and test code 

### ISSUE THREAD

**Issue by TestSmell** [eclipse-openj9/openj9#15708]
Hi!
We notice that there is a test smell in your code organization.
Based on our analysis of the answers in relevant Stack Overflow posts, the best practice for code organization of a project needs to comply with two conventions:
1. separate test code with production code
2. use a parallel package structure to organize production and test code, like a maven structure

In your project, you follow the first conversion, i.e., you are not mixing test code with the production-code-under-test since you place all your test code in the ''test'' folder, but you are not using a more clear folder structure to organize the relationships between test code and production code. 
It is hard for you to quickly find the corresponding test files of a production code fragment after a long time, increasing your maintenance cost.

Thus, we sincerely suggest that you can re-organize your test code in a proper folder structure. :-D

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
Could you please elaborate on `you are not using a more clear folder structure to organize the relationships between test code and production code`? Do you have any specific suggestions regarding re-organization? Thanks

**Comment by TestSmell** [comment]
This is your test code organization:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/110402847/184818709-07e94ac0-bb03-4d8a-a403-d286edc58f09.png">

The folder names of your test code have no mappings to your production code.
It is against the best practice of code organization: use a parallel package structure to organize production and test code, like a maven structure.
For example, ''openj9/test/Utils/src/org/openj9/test/util/'' is one of the folders of your test code. But it is hard for me to find the corresponding code-under-test. 
According to the best test practice, you should create a parallel folder (i.e., '''openj9/main/Utils/src/org/openj9/main/util/'') and place the code-under-test into the parallel folder, or vice versa.  Thank you.

**Comment by smlambert** [comment]
While your recommendations are interesting, we may not be addressing them in the recommended way you suggest.  Please point to the recommended best practices that you allude to, and your affiliation.  Thanks.

Here is the current organization:
- test/docs contains the documentation for the tests
- test/TestConfig are shared configuration for the tests
- test/Utils are shared utility code for the tests
- test/functional contains test material organized in a particular and specifically chose way.  Since it is not all are 'unit' tests, it would not be feasible or necessarily correct to organize it to match the structure of the product code.

**Comment by smlambert** [comment]
Closing as won't fix
