### ISSUE TITLE
Add simple docker based AOT test

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#15740]
In 0.33, we had AOT incompatibility problem (see https://github.com/eclipse-openj9/openj9/issues/15697), we would like to add a simple docker based AOT test. In aqa-test repo, add `aot` folder in external https://github.com/adoptium/aqa-tests/tree/master/external. It runs `java -Xjit:verbose -version` in docker (i.e., ibm-semeru-runtimes:open-17-jdk) and we should not see `AOT header validation failed` in the output.

**Comment by llxia** [comment]
@LongyuZhang could you help to add the test? Thanks

**Comment by LongyuZhang** [comment]
Hi @mpirvu, 
in current docker image `ibm-semeru-runtimes:open-17-jdk`, we can reproduce this error (the docker image was updated 8 days ago [link](https://hub.docker.com/r/amd64/ibm-semeru-runtimes/tags)).

I am wondering if mounted jdk works for this case? So far the error with mounted jdk is `AOT header validation failed: bad header version or version string`

Detailed steps for the mounted jdk:
- On skylake machine, download jdk `https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_linux_Nightly/298/OpenJ9-JDK17-x86-64_linux-20220818-191547.tar.gz` and unzip.
- `docker run -v /home/jenkins/deleteMe/jdk:/opt/java/openjdk --rm -it ibm-semeru-runtimes:open-17-jdk /opt/java/openjdk/bin/java -Xjit:verbose -version`

In addition, does AOT works only  for version 11+? Thanks.

**Comment by mpirvu** [comment]
AOT should work for all versions of Java

The problem is that the SCC that is embedded in the Semeru containers was created with a JDK that has the problem.
These kind of problems appear when you take the SCC created on one system and use it on another system. Embedding the SCC in a containers achieves this situation.

What we need here is to actually create an OpenJ9 image using the same Dockerfile Semeru uses, on a newer architecture, and then execute "docker run --rm -it SemeruImage java -Xjit:verbose -version" on an older acrhitecture and make sure that AOT code can be used

**Comment by LongyuZhang** [comment]
Thanks for the explanation. If I understand correctly, In this case for the simple aot test, we just need to test the jdk inside the docker image. Then for the portable aot test, we need to create a docker image with new JDK, then test it on another architecture.

**Comment by llxia** [comment]
Thanks @LongyuZhang . Close this issue as the PR is delivered.
