### ISSUE TITLE
Unable to generate a javacore without the process ending at checkpoint

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#15776]
See https://github.com/eclipse-openj9/openj9/issues/15771 for details.

When running with `-Xtrace:trigger=tpnid{j9criu.7-8,javadump}` or `-Xtrace:trigger=method{org/eclipse/openj9/criu/CRIUSupport.checkpointJVM,javadump,javadump}`, the JVM manages to generate a javacore, but fails to subsequently checkpoint.

**Comment by ymanton** [comment]
Try running with `-Xsyslog:none`.

**Comment by dsouzai** [comment]
`-Xsyslog:none` worked; thanks @ymanton. Why does this option fix things?

**Comment by ymanton** [comment]
We open the syslog at startup and never close it. Normally that's fine, but the implementation of syslog can involve opening a socket to a daemon to send the messages to, which is what causes the problem. I'm guessing that the socket connection is actually opened lazily, so opening the syslog doesn't open the underlying socket, actually sending something to the log does.

According to the docs[^1] we log error and vital messages by default, and vital includes dump messages, so that would explain why when you trigger a dump we see the syslog socket open when CRIU attempts to dump the process.

In checkpoint mode we should close and re-open the syslog across the C/R cycle. Hopefully closing the syslog handle actually closes the underlying socket promptly, otherwise it won't fix anything. FYI @tajila.

[^1]: https://www.eclipse.org/openj9/docs/xsyslog/#vital

**Comment by tajila** [comment]
Thanks @ymanton Ill give that a try

**Comment by JasonFengJ9** [comment]
> Hopefully closing the syslog handle actually closes the underlying socket promptly, otherwise it won't fix anything.

A quick experiment shows that adding `j9port_control(OMRPORT_CTLDATA_SYSLOG_CLOSE, 0)` before doing checkpoint fixes the failure w/ `-Xtrace:trigger=tpnid{j9criu.7-8,javadump}`.

After restore, the `syslog` need to be re-opened using same `xlogflags` for initial opening, a draft PR is in progress.
