### ISSUE TITLE
CRIU: ElapsedTime sample doesnt work properly with jit enabled

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15991]
When running the https://github.com/ibmruntimes/InstantOnStartupGuide/blob/main/Samples/ElapsedTime.java app, the result should show 

```
Spin for 10 seconds
..........
Total number of sleeps 10
```

With C/R jit enabled it shows

```
/instantOnDemo# bash Scripts/restore.sh
....
Total number of sleeps 9
```

With C/R -Xint

```
/instantOnDemo# bash Scripts/restore.sh
.....
Total number of sleeps 10
```

We are losing a bit over 1second between checkpoint and restore with JIT enabled.

**Comment by tajila** [comment]
@0xdaryl  @dsouzai 

I think the cause may be that the jit is using a different clock than the interpreter?

**Comment by dsouzai** [comment]
I printed out the values returned by `System.nanoTime()`. 

Xint
|Invocation|System.nanoTime() value|Diff from previous invocation|
|--|--|--|
|final long start|101987809291570|na|
|1|101987889582458|80290888|
|2|101988890316671|1000734213|
|3|101989890953395|1000636724|
|4|101990891199687|1000246292|
|5|101991891427926|1000228239|
|checkpoint|na|na|
|6|101992936805320|1045377394|
|7|101993937342433|1000537113|
|8|101994937722014|1000379581|
|9|101995938142404|1000420390|
|10|101996938531098|1000388694|
|loop terminates|101997938915939|1000384841|


Xjit
|Invocation|System.nanoTime() value|Diff from previous invocation|
|--|--|--|
|final long start|102020072030144|na|
|1|102020167298352|95268208|
|2|102021168490409|1001192057|
|3|102022169512243|1001021834|
|4|102023169868865|1000356622|
|5|102024170260188|1000391323|
|checkpoint|na|na|
|6|102026207080676|2036820488|
|7|102027207986861|1000906185|
|8|102028208355831|1000368970|
|9|102029208801633|1000445802|
|loop terminates|102030209285695|1000484062|

In in the -Xjit case, the diff between the `System.nanoTime()` invocations across a C/R is consistently ~2s rather than 1s. Now, this happens even if I run with `-Xjit:exclude={*}`, so we're not even executing any JIT code. It also doesn't seem to matter how long I wait before running the restore.

I remembered the EA build has that sleep the JIT does to allow the comp threads to empty the compilation queue. So I ran with `-Xjit:sleepMsBeforeCheckpoint=0` and that seems to fix the problem. It looks like `System.nanoTime()` is reflects the time spent doing all that work in the VM hooks.

The code in the master branch does not have the sleep, but it does wait for compilations to finish; additionally if we start doing preemptive compilation, there's going to be a bunch of time spent waiting for them to finish. So, I think the logic that compensates `nanoTime` needs to be revisited.

**Comment by tajila** [comment]
@dsouzai thanks. Yes that makes sense.

**Comment by tajila** [comment]
@JasonFengJ9 can you make a PR that records the time delta before and after the internal hook
