### ISSUE TITLE
jdk19 Jep425Tests_testVirtualThread_0 hangs

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16011]
Jep425Tests_testVirtualThread_0 in sanity.functional testing is hanging, on alinux, aix, plinux, xlinux, windows. Not on amac, zlinux, xmac.

This was first seen in PR testing https://github.com/eclipse-openj9/openj9/pull/16002#issuecomment-1261482980
also seen in the OMR acceptance build https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/379/
Did not occur in the nightly build last night https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/164/

I believe that makes the culprit one of these changes.
https://github.com/eclipse-openj9/openj9/compare/cb8605da243...02c3cf1f9e79c

https://github.com/eclipse-openj9/openj9/pull/15968 - PR tested on alinux
https://github.com/eclipse-openj9/openj9/pull/15612 - PR tested on xlinux
https://github.com/eclipse-openj9/openj9/pull/15996 - PR tested on amac, which is a passing platform.

@fengxue-IS @babsingh pls take a look.

**Comment by babsingh** [comment]
- The hang happens due to https://github.com/eclipse-openj9/openj9/pull/15996.
- Created https://github.com/eclipse-openj9/openj9/pull/16016 to revert it.
- See javacore; all vthreads and their carrier threads are parked: [javacore.20220929.085955.17624.0001.txt](https://github.com/eclipse-openj9/openj9/files/9676374/javacore.20220929.085955.17624.0001.txt).
