### ISSUE TITLE
J9 's JDK8 reports NoSuchMethodError, but the JDK11 is normal.

### ISSUE THREAD

**Issue by JitRevealer** [eclipse-openj9/openj9#16034]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Windows 10:

```
Microsoft Windows 10 Professional
10.0.19044 Build 19044
AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
Memory 32 GB
```

Java -version output under Windows 10

```
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```

```
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
```

## Problem summary

The decompiled code for the test case is shown below. Because the issue can not be reproduced in the source code, so we submit the related class file. In the decompiled code, we try to use `StringBuilder.append ()` function, but OpenJDK8's execution result report `Java. Lang. NoSuchMethodError`. It is worth noting that the test case terminates normally when executed with OpenJDK11. 

```java
class TestCase1 {
    TestCase1() {
    }
    public static void main(String[] var0) {
        StringBuilder var28 = new StringBuilder();
        var28.append(new Object());
    }
}
```

## Attachment
[TestCase1.zip](https://github.com/eclipse-openj9/openj9/files/9705337/TestCase1.zip)

**Comment by pshipton** [comment]
Occurs with -Xint. In incompatibility related to AbstractStringBuilder.
```
Exception in thread "main" java.lang.NoSuchMethodError: java/lang/StringBuilder.append(Ljava/lang/Object;)Ljava/lang/AbstractStringBuilder; (loaded from /home/peter/jdk8u332-b09/jre/lib/rt.jar by <Bootstrap Loader>) called from class TestCase1 (loaded from file:/home/peter/ by sun.misc.Launcher$AppClassLoader@b9d0b20b).
``

**Comment by pshipton** [comment]
I don't see any reason to fix this, it doesn't seem like a real problem that occurs in the real world. The failure occurs because OpenJDK defines a non-public AbstractStringBuilder class, which isn't part of the java specification. The StringBuffer and StringBuilder classes extend it, although the Java specification doesn't show this. OpenJ9 added the abstract class for compatibility many year ago, before OpenJ9 was open sourced, but it doesn't implement any methods. To fix the failure, and other possible failures, the OpenJ9 AbstractStringBuilder would need to implement the same methods as the non-spec'ed class in OpenJDK.

It only occurs on jdk8 because OpenJ9 only provides AbstractStringBuilder, StringBuffer, StringBuilder implementations on this version. From Java 11, the OpenJDK provided classes are used.
