### ISSUE TITLE
which branch/tag should I choose if I want to compile/build an arm32 version of openj9 by myself?

### ISSUE THREAD

**Issue by linfaimom** [eclipse-openj9/openj9#16269]
There's now no arm32 version that I could download~~

**Comment by pshipton** [comment]
OpenJ9 does not support arm32.
@knn-k @0xdaryl fyi

**Comment by 0xdaryl** [comment]
@pshipton is correct.  The J9 VM technology has supported arm32 in the past but not since it has been contributed to open source.  Even though much of the source code is still present in the repo, it is extremely stale and likely won't build and run as-is.  This code may be removed from OpenJ9 in the near future.

**Comment by linfaimom** [comment]
Got it, thanks for your quick response!
