### ISSUE TITLE
Too many AOT load failures with -Xaot:forceaot

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#16402]
During an experiment with Liberty+AcmeAir app that was using -Xaot:forceaot I collected the following compilation stats:

```
OptLvl  Samples TOTAL(ms)       MIN(usec)       AVG(usec)       MAX(ms)
Total     15445   369863              22           23947        5752.2
 aotl      3664     2477              22             676          76.8
  jni       189      117             182             617           8.3
 cold      1120    18236             195           16282         200.8
 warm      2438   157492             269           64599        3357.0
 aotw      8028   179779             175           22394        2459.4
  hot         6    11763           59590         1960456        5752.2
 fail       985    10446              55           10605        2221.3


Failure reasons:
compilationRelocationFailure = 486
compilationAotHasInvokehandle = 45
compilationAotHasInvokeVarHandle = 23
compilationAotHasInvokeSpecialInterface = 2
compilationAotCacheFullReloFailure = 16
compilationSymbolValidationManagerFailure = 411
compilationHeapLimitExceeded = 1
compilationInterrupted = 1
```
This is a cold run (starts with an empty SCC) and we have 8028 AOT compilations. After they get more invocations, some of these methods will be loaded from SCC, relocated and placed into the code cache. We see 3664 successful AOT loads and 495 failures related to AOT load operations. This is a large percentage (12%) of AOT load failures during the run that produced the AOT bodies.

Out of the 495 AOT load failures, 457 are due to "isClassVisibleValidationFailure".
Other reasons include: classByNameValidationFailure=20 occurrences, blockFrequencyRelocationFailure=9 occurences, symbolFromManagerRelocationFailure=9 occurrences

**Comment by mpirvu** [comment]
We also see 489 "AOT warm" compilation failures out of which 411 are due to `compilationSymbolValidationManagerFailure`

**Comment by mpirvu** [comment]
Attn: @dsouzai

**Comment by dsouzai** [comment]
With https://github.com/eclipse-openj9/openj9/pull/16476, the actual error seen during the load is `j2iThunkFromMethodValidationFailure`. I was able to reproduce this even with Liberty+DT7. What's interesting is that not all j2i thunk validations fail. After taking a closer look, it looks like the failures happen when a validation results in a thunk that was associated to a previous validation record, eg:
```
TR_RelocationRecordValidateJ2IThunkFromMethod 00007F0005FE3174
        size 10 type 110 flags 80 reloFlags 0
        Flag: Wide offsets
        methodID 35
        thunkID 49
        reloLocation: from 00007F0005FE3180 at 00007F000000AF60 (offset d36690a0)
                relocateAndRegisterThunk: (Ljava/lang/Object;)Z
                        relocateAndRegisterThunk: found matching thunk 00007F002C9A48D8
TR_RelocationRecordValidateJ2IThunkFromMethod 00007F0005FE3184
        size 10 type 110 flags 80 reloFlags 0
        Flag: Wide offsets
        methodID 37
        thunkID 50
        reloLocation: from 00007F0005FE3190 at 00007F000000AF60 (offset d36690a0)
                relocateAndRegisterThunk: (Ljava/util/HashMap$Node;)V
                        relocateAndRegisterThunk: found matching thunk 00007F002C9A4CB8
        applyRelocationAtAllOffsets: rc = j2iThunkFromMethodValidationFailure
```
This is curious because as per https://github.com/eclipse-openj9/openj9/blob/a2475ea96ca342c049bf8784da91e84d887ad448/runtime/compiler/runtime/SymbolValidationManager.cpp#L1094 if there was a thunk that could be shared, we wouldn't have generated another validation record.

After going through the code, I believe the issue is caused by the fact that `getJ2IThunk` and `setJ2IThunk` is overridden in the AOT Frontend. The thunk is looked up and generated (if needed) at https://github.com/eclipse-openj9/openj9/blob/a2475ea96ca342c049bf8784da91e84d887ad448/runtime/compiler/x/codegen/X86PrivateLinkage.cpp#L1776-L1778

The non-AOT frontend looks up the thunk in some hashtable, and returns it; if it doesn't exist, a new thunk is created and stored to the hashtable. The AOT frontend however, looks up/stores the thunks from the SCC. While the non-AOT frontend version can result in sharing even if there are differences in the signature of the thunk, the AOT frontend does not result in the same sharing. As such, during the compile run, different thunks are generated.

At load time however, before looking up the thunk in the SCC, the code looks up the thunks in the hashtable (i.e., what is done normally for a non-AOT compile). This now results in sharing of thunks that wasn't possible when only using the SCC.

I'll need to think about this one and talk to @jdmpapin (when he's back from vacation); the relocation code is shared between multiple relocation/validation records, so I need to make sure that the fix doesn't break something else.

**Comment by dsouzai** [comment]
I looked into the hastable implementation to understand how we can have thunk sharing. Based on 
https://github.com/eclipse-openj9/openj9/blob/a2475ea96ca342c049bf8784da91e84d887ad448/runtime/codert_vm/thunkcrt.c#L191-L204
and taking into account
https://github.com/eclipse-openj9/openj9/blob/a2475ea96ca342c049bf8784da91e84d887ad448/runtime/codert_vm/thunkcrt.c#L325
it looks like as long as two signatures have the same primitive type arguments in the same place, and object arguments in the same place (even if they are different object types), the thunk can be shared.

I spoke to Marius and he suggested that it may be worth exposing the code in
https://github.com/eclipse-openj9/openj9/blob/a2475ea96ca342c049bf8784da91e84d887ad448/runtime/codert_vm/thunkcrt.c#L400
such that we can reuse the encoding for the purposes of storing thunks to the SCC. This would result in AOT compiles having the same sharing that occurs in non-AOT compiles.

**Comment by mpirvu** [comment]
[`j9ThunkEncodeSignature(char *signatureData, U_8 * encodedSignature)`](https://github.com/eclipse-openj9/openj9/blob/master/runtime/codert_vm/thunkcrt.c#L303)  is probably what we want to re-use for SCC

**Comment by jdmpapin** [comment]
I agree that we should reuse `j9ThunkEncodeSignature()` to key J2I thunks stored in the SCC. I wonder how much space we're currently wasting on unnecessarily duplicated thunks
