### ISSUE TITLE
Why does OpenJ9 require less memory footprint than HotSpot?

### ISSUE THREAD

**Issue by NAOnlyOne** [eclipse-openj9/openj9#16500]
I can't find a reason from any article why OpenJ9 needs less memory footprint than HotSpot.
In the official documentation description, at steady state, OpenJDK 8 with OpenJ9 was found to use approximately 63% less physical memory than OpenJDK 8 with HotSpot.

**Comment by pshipton** [comment]
@dmitripivkine @mpirvu fyi in case you want to take a stab at this.

**Comment by mpirvu** [comment]
From the Java heap point of view, OpenJ9 is less aggressive in growing the heap. I'll let @dmitripivkine or @amicic comment on that.
From the JIT point of view, all the "scratch" memory that is used during JIT compilation (which could be in the hundreds of MB) is released back to the OS at the end of the compilation. This is possible because OpenJ9 uses VirtualAlloc/mmap to allocate scratch memory rather than malloc (malloc keeps freed memory in its internal pools for future reuse).

**Comment by dmitripivkine** [comment]
Closing... If you need more details please reopen
