### ISSUE TITLE
JVMTI NotSuspended test fails with incorrect virtual thread stacktrace

### ISSUE THREAD

**Issue by dipak-bagadiya** [eclipse-openj9/openj9#16688]
### Issue
The stacktrace of virtual thread is incorrect since it doesn't start/match the `CONTINUATION_CLASS_NAME`
and `CONTINUATION_METHOD_NAME`.

### Test CMD
```
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/stress/StackTrace/NotSuspended" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"
```

### Test Output
```
STDOUT:
Agent_OnLoad started
Agent_OnLoad finished
Synchronization point checkStatus(0) called.
Data 0x7f2f740a4bd8 0x7f2f54002b18
Agent: wait for thread to start
Agent: started
Agent: Stacktrace of virtual thread is incorrect: doesn't start from enter(...):
JVMTI Stack Trace: frame count: 6
 0: java/lang/Object: waitImpl(JI)V
 1: java/lang/Object: wait(JI)V
 2: java/lang/Object: wait(J)V
 3: java/lang/Thread: join(J)V
 4: java/lang/Thread: join()V
 5: com/sun/javatest/regtest/agent/MainWrapper: main([Ljava/lang/String;)V
```

**Comment by babsingh** [comment]
@fengxue-IS I believe that this test fails because our implementation of `Continuation` does not match the RI. Do you agree? If so, do you want to match the RI or permanently exclude the test?

**Comment by fengxue-IS** [comment]
This is not due to mismatch of the impl, looking at the test code, seem like we have returned a carrier/platform thread as result of `GetVirtualThread` call, this should be fixed in `jvmtiGetVirtualThread` code.

The test code seem to suggest that a `JVMTI_ERROR_THREAD_NOT_ALIVE` error should be returned when the platform thread passed into `GetVirtualThread` doesn't have a virtual thread mounted.

Once that have been fixed, we should retest to see if it is still looking at implementation specific details. (I suspect that will be the case as OpenJ9's continuation entry point is `Continuation.execute(...)` instead of the `enter(...)` expected by the test case.

**Comment by babsingh** [comment]
`NotSuspended/GetStackTraceNotSuspendedStressTest` has been enabled in https://github.com/adoptium/aqa-tests/pull/4554.

The test was fixed through the following PRs:
- https://github.com/eclipse-openj9/openj9/pull/16786;
- https://github.com/eclipse-openj9/openj9/pull/16787; and
- https://github.com/eclipse-openj9/openj9/pull/17318.
