### ISSUE TITLE
Jep389Tests_testClinkerFfi_UpCall test_addDoubleAndIntDoubleLongFromStructByUpcallMH expected but found

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17071]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_0/437
Jep389Tests_testClinkerFfi_UpCall_0
```
01:30:34  FAILED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH
01:30:34  java.lang.AssertionError: expected [8.89000000732344E11] but found [1.11112050344E8]
01:30:34  	at org.testng.Assert.fail(Assert.java:96)
01:30:34  	at org.testng.Assert.failNotEquals(Assert.java:776)
01:30:34  	at org.testng.Assert.assertEquals(Assert.java:489)
01:30:34  	at org.testng.Assert.assertEquals(Assert.java:502)
01:30:34  	at org.openj9.test.jep389.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndIntDoubleLongFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:889)
```

**Comment by pshipton** [comment]
10x x 3 grinder https://openj9-jenkins.osuosl.org/job/Grinder/2149/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_Nightly_testList_0/140
Jep424Tests_testLinkerFfi_UpCall_0
```
04:00:39  FAILED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH
04:00:39  java.lang.AssertionError: expected [8.89000000732344E11] but found [1.11112050344E8]
04:00:39  	at org.testng.Assert.fail(Assert.java:96)
04:00:39  	at org.testng.Assert.failNotEquals(Assert.java:776)
04:00:39  	at org.testng.Assert.assertEquals(Assert.java:489)
04:00:39  	at org.testng.Assert.assertEquals(Assert.java:502)
04:00:39  	at org.openj9.test.jep424.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndIntDoubleLongFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:851)
```

**Comment by pshipton** [comment]
As per the grinder, it's not intermittent.

Changes
https://github.com/eclipse-openj9/openj9/compare/43d1e8c2357...c797e9f2412
https://github.com/eclipse-openj9/openj9-omr/compare/c766c4155b0...3c7f2362046

@ChengJin01 pls take a look.

**Comment by ChengJin01** [comment]
It turns out that the outdated test code in JDK17 & 19 at https://github.com/eclipse-openj9/openj9/pull/17014/files#diff-6b3fb2be858ba9873e0a110806a36a4fabc0e36fb8c7e9d60a0e80a885c50891 and https://github.com/eclipse-openj9/openj9/pull/17014/files#diff-82192affb0ec8a14a7a15bdece859e003c4295d9ac65331c90c8f92d9ce0b909 overwrote the latest fix at https://github.com/eclipse-openj9/openj9/pull/16835 when updating the tests for JDK20 (likely didn't rebase correctly in 17014)

I will update the test code to restore the fix at 16835.
