### ISSUE TITLE
JIT generated code must avoid using arraycopy instruction if a NullPointerException could result

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#17196]
Under Valhalla prototype support in OpenJ9, primitive value types do not allow null references.  A cast of a null reference to a primitive value type class must throw a `NullPointerException`, and assignment of a null reference to an array whose component type is a primitive value type class must throw a `NullPointerException`.

Similarly, `System.arraycopy` will throw a `NullPointerException` if the source array contains a null reference that is copied to the target array, and the component type of the target array is a primitive value type class.  This change is being implemented in OpenJ9 pull request #17048.

Currently, the JIT will often attempt to use an `arraycopy` instruction in place of a call to `System.arraycopy`.  However, the implementation of that instruction only allows for the possibility of an `ArrayStoreException`.

In an off-line discussion between Vijay @vijaysun-omr, Daryl @0xdaryl, Annabelle @a7ehuo and myself, it was decided that the case where a `NullPointerException` is possible is very unlikely.  Rather than changing the implementation of the `arraycopy` instruction to allow for the unlikely case that an `NullPointerException` might be thrown, the JIT should instead prevent the use of that instruction if a `NullPointerException` could be thrown.

This can be accomplished with a combination of run-time tests of the component types of the arrays and recognition at compile-time of cases where the component types could result in a `NullPointerException`.  The `arraycopy` instruction would only be executed or generated, respectively, if a `NullPointerException` could never occur; the actual call to `System.arraycopy` would be used if a `NullPointerException` could occur.

**Comment by a7ehuo** [comment]
I have a prototype on https://github.com/a7ehuo/omr/commit/281f85bdbccb686dccdaa3ce3e3fb4f2c38c8c00 which can pass simple `System.arraycopy` call tests. I'm still looking at how to optimize the implementation since the children from the call node have to be saved to temps a few times in order to common the nodes after splitting the blocks. 

While experimenting the prototype, I found an issue with the existing implementation of `System.arraycopy` with flattened value type arrays: https://github.com/eclipse-openj9/openj9/issues/17586. I might take a look at #17586 first before proceeding further with this prototype.
