### ISSUE TITLE
JEP 446: Scoped Values (Preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17488]
See [Scoped Values (Preview)](https://openjdk.org/jeps/446)

**Comment by pshipton** [comment]
@tajila @babsingh @fengxue-IS

**Comment by babsingh** [comment]
Currently, in JDK20, there is only one failure associated to Scoped Values: https://github.com/eclipse-openj9/openj9/issues/16965; this has been identified as a JIT inliner issue. Will keep monitoring the JEP's state periodically.

**Comment by babsingh** [comment]
Current tests in JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/tree/openj9/test/jdk/jdk/incubator/concurrent/ScopedValue

Currently, only the `StressStackOverflow` test is disabled. References:
- JDK20: https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20-openj9.txt
- JDK21: https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk21-openj9.txt

**Comment by babsingh** [comment]
Most of the work for scoped values is complete.

The two remaining tasks have individual issues and can be tracked through the [Java 21 milestone](https://github.com/eclipse-openj9/openj9/milestone/45):
- https://github.com/eclipse-openj9/openj9/issues/16965
- https://github.com/eclipse-openj9/openj9/pull/17402

Closing since this issue is no longer needed.
