### ISSUE TITLE
Class verification support for regulated constructor in Project Valhalla

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#18309]
In the latest JEP401, a "regulated" constructor is introduced:

`The constructor of a value class is regulated, meaning that its body must not make any use of this, except to write to an instance field. This ensures a value object does not "escape" to the rest of the program during construction.`

More details can be found in the [JEP](https://openjdk.org/jeps/401).

The regulated constructor will be represented by modifier `0x0800` in the class file.
Class format check should fail if a value class defines a non-regulated constructor. RT verification may need to be updated as well.

**Comment by hangshao0** [comment]
FYI @ChengJin01

**Comment by hangshao0** [comment]
This is gone in the latest spec. Closing this.

**Comment by hangshao0** [comment]
@llxia It seems more reasonable to not trigger https://github.com/eclipse-openj9/openj9/issues/18309#issuecomment-2392296888 when closing an issue.

**Comment by llxia** [comment]
https://github.com/eclipse-openj9/openj9/issues/18309#issuecomment-2392296888 is used to document the actual assigned components and assignees. It enables us to gather the actual values for comparison against the recommended values in the future. This issue was opened before triagerx was enabled. Otherwise, it would have the comment about the recommended components and assignees.

The plan is to let triagerx run for a while and reassess it later. We welcome your feedback in the upcoming survey.
