### ISSUE TITLE
JITServerSharedROMClassCache double-initialization after purging all client session data triggers assert

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#18631]
During a purge operation, the JITServer will delete client session data:

https://github.com/eclipse-openj9/openj9/blob/4af048afaac0a64074c489e25ca82f2078e5c6af/runtime/compiler/runtime/JITClientSession.cpp#L1229-L1243

It is possible for this operation to delete every entry in the `_clientSessionMap`. If it does, the next time a client connects, this code will run:

https://github.com/eclipse-openj9/openj9/blob/4af048afaac0a64074c489e25ca82f2078e5c6af/runtime/compiler/runtime/JITClientSession.cpp#L1122-L1127

However, the shared ROM class cache will have already been created, leading to an assert triggering in `initialize()`:

https://github.com/eclipse-openj9/openj9/blob/4af048afaac0a64074c489e25ca82f2078e5c6af/runtime/compiler/runtime/JITServerSharedROMClassCache.cpp#L129

I think the purge operation may need to check if `_clientSessionMap` is empty post-purge, and shut down the shared ROM class cache if it is. You can see that the `deleteClientSession()` function does this properly:

https://github.com/eclipse-openj9/openj9/blob/4af048afaac0a64074c489e25ca82f2078e5c6af/runtime/compiler/runtime/JITClientSession.cpp#L1172-L1177

**Comment by cjjdespres** [comment]
Attn @mpirvu. I can put up a fix when I get a chance.

**Comment by cjjdespres** [comment]
Just to note what we talked about: it's not immediately obvious that we should shut down the shared ROM class cache once the last client disconnects, so maybe the `deleteClientSession()` should be changed instead. That might introduce a problem with unbounded growth of the shared ROM class cache for long-running JITServer instances, though.

**Comment by mpirvu** [comment]
The way I am reading the code is the following:
- the purge operation may delete the last attached client and in that case it calls `JITServerSharedROMClassCache::shutdown(bool lastClient)`
- `JITServerSharedROMClassCache::shutdown()` deletes the entire ROMClassCache including the persistent allocator used for allocating space for ROMClasses. At the very end it sets `_persistentMemory = NULL`
- When a new client connects, it checks `_clientSessionMap.empty()` which is true, and then proceeds to do another cache initialization. 
- Inside `JITServerSharedROMClassCache::initialize()` there is the assert ` TR_ASSERT(!isInitialized(), "Already initialized");` but this should not trigger because `isInitialized()` looks at `_persistentMemory` field which was set to NULL.

**Comment by mpirvu** [comment]
> I think the purge operation may need to check if _clientSessionMap is empty post-purge, and shut down the shared ROM class cache if it is.

I agree with this
