### ISSUE TITLE
Attach wait loop only recreates missing notification files if the entire notification directory has been deleted

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#18679]
Here's a test that demonstrates some interesting behaviour involving the Attach API. We'll use two small programs:

```
public class InfiniteSleep {
	public static void main (String args[]) throws Exception {
		Thread.sleep(Long.MAX_VALUE);
	}
}
```

```
public class JVMLister {
	public static void main(String[] args) {
		for (Object jvm : com.sun.tools.attach.VirtualMachine.list().toArray()) {
			System.out.println(jvm);
		}
	}
}
```

1. Compile and run InfiniteSleep
2. Compile and run JVMLister. Note that two JVMs are listed - the JVM running the JVMLister program, and the JVM running the InfiniteSleep program.
3. Delete the files in `/tmp/.com_ibm_tools_attach/[PID]`, where `[PID]` is the process ID for the JVM running the InfiniteSleep program.
4. Run JVMLister again. Only the JVM running the JVMLister program is listed.
5. Run JVMLister again. Both JVMs are listed again, as they were in step (2).

This happens because on step (4) the implementation of `com.sun.tools.attach.VirtualMachine.list()` notices the missing files in the PID subdirectory, interprets the directory as "stale", and cleans up by deleting the whole directory here:

https://github.com/eclipse-openj9/openj9/blob/f0527342f6330bdf7544dda1487442aaadedabd3/jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java#L185C13-L188

Once the PID directory is deleted, the Attach wait loop in the JVM running the InfiniteSleep program quickly notices that it's missing and recreates the directory and the files within, here:

https://github.com/eclipse-openj9/openj9/blob/f0527342f6330bdf7544dda1487442aaadedabd3/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java#L89-L120

The problem is that this code in the Attach wait loop doesn't check for the scenario where the PID directory still exists, but the files within it have been deleted. Can this code be improved to check for the existence of the files in the directory as well as the directory itself, and then reconstruct the files if they are missing?

**Comment by JasonFengJ9** [comment]
Run the testcase w/ `-Dcom.ibm.tools.attach.logging=yes`, the log files show the following file creation sequences:

**Before** the step 3 - Delete the files in `/tmp/.com_ibm_tools_attach/[PID]`, where `[PID]` is the process ID for the JVM running the InfiniteSleep program.
```
1704225631277(Tue Jan 02 15:00:31 EST 2024) 76150: 26 [Attach API wait loop]: iteration 0 waitForNotification ignoreNotification entering
1704225631277(Tue Jan 02 15:00:31 EST 2024) 76150: 26 [Attach API wait loop]: iteration 0 waitForNotification ignoreNotification entered
1704225631277(Tue Jan 02 15:00:31 EST 2024) 76150: 26 [Attach API wait loop]: iteration 0 waitForNotification starting wait
```
This JVM was at https://github.com/eclipse-openj9/openj9/blob/f0527342f6330bdf7544dda1487442aaadedabd3/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java#L68
Deleting the files in `/tmp/.com_ibm_tools_attach/[PID]` won't be detected by this JVM.

Run JVMLister,  only the JVM running the JVMLister program is listed. This is because there is no `attachInfo` file within the `[PID]` in question. `com.sun.tools.attach.VirtualMachine.list()` only deletes this empty `stale` folder when `(myUid == 0) || (uid == myUid)`.
https://github.com/eclipse-openj9/openj9/blob/f0527342f6330bdf7544dda1487442aaadedabd3/jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java#L185-L187
In my test environment, this deletion didn't happen. I think this won't affect the InfiniteSleep program since it is still `waitSemaphore()`.

The InfiniteSleep program exits `waitSemaphore()` when the `JVMLister` exits and invokes `notifyVm()` https://github.com/eclipse-openj9/openj9/blob/7cba421b926a5ec0efa8069a80f33e1513677cf0/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java#L499
```
1704225706840(Tue Jan 02 15:01:46 EST 2024) 76194: 24 [Attach API teardown]: AttachHandler.terminateWaitLoop_2_notifyVm 2 targets
```

The InfiniteSleep program detects the file `attachInfo` missing
https://github.com/eclipse-openj9/openj9/blob/7cba421b926a5ec0efa8069a80f33e1513677cf0/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/TargetDirectory.java#L240
and re-create the directory/file
https://github.com/eclipse-openj9/openj9/blob/7cba421b926a5ec0efa8069a80f33e1513677cf0/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/TargetDirectory.java#L244-L248

I modified the `JVMLister` to run `VirtualMachine.list()` multiple times before exiting, it still can't detect the InfiniteSleep program if its `attachInfo` file is deleted. Only exiting and re-launching can find it again.

The InfiniteSleep program only checks its Advertisement file `attachInfo` after receiving a notification, and won't do so while `waitSemaphore()` unless it wakes and checks it periodically (still there is a time hole). Considering the file deletion is a user action, I feel this is a limitation.

@paulcheeseman @pshipton thoughts?

**Comment by paulcheeseman** [comment]
I misread the code and my initial problem description was wrong. Apologies for that.

I was working under the assumption that the wait loop was already periodically waking up to check the notification files, and that the checking was not working optimally, but clearly I was wrong. The part I missed was this:

> The InfiniteSleep program exits waitSemaphore() when the JVMLister exits and invokes notifyVm()

I didn't realise that the JVMLister process's exit was causing the InfiniteSleep JVM's attach handler thread to wake up.

So the JVM whose files we're deleting does in fact already detect the problem with the files and fix them itself, but only when its attach handler thread is brought out of the wait loop by another JVM.

It would certainly help in this scenario if the attach handler thread were to wake up and check the files regularly, but as you say, even then there would still be a delay before any missing files were recreated. I'm also not convinced that the extra complexity is worth it given that the situation itself should be completely avoidable - I can't think of any valid reason to delete those files.

For context, I have a customer who encountered this issue because their notification files are being deleted by some external actor, the identity of which is currently unknown.

**Comment by JasonFengJ9** [comment]
Assuming no VM action, closing.
@paulcheeseman feel free to re-open if needed.
