### ISSUE TITLE
Remove _magic_ constant `J9_FFI_DOWNCALL_HEAP_ARGUMENT_ID`

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#19005]
`J9_FFI_DOWNCALL_HEAP_ARGUMENT_ID` was originally `0x1`, but changed to `0xFFFFFFFFFFFFFFFF` in #19002. No matter what value is chosen, it's possible it conflicts with application intent. As I [suggested](https://github.com/eclipse-openj9/openj9/pull/19002#discussion_r1500734712), I think we should use an out-of-band channel to distinguish parameters that should point within the heap from other parameters.

**Comment by ChengJin01** [comment]
Instead of relying on `J9_FFI_DOWNCALL_HEAP_ARGUMENT_ID ` which causes conflict with the malicious address imposed by users, I think the problem can be resolved by checking the existence of `heapBase`  in which case `heapBase` is set to `null` in terms of a native array (a non-null `heapBase` object denotes a heap array). I will create a patch with the solution to see whether it works good as expected.
