### ISSUE TITLE
An issue of OpenJ9-11 checking bytecode files for minor version

### ISSUE THREAD

**Issue by TemporaryRepos** [eclipse-openj9/openj9#19129]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Linux Ubuntu20.04

Java -version output under Linux

```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_861 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)
```

```
openjdk version "11.0.22" 2024-01-16
IBM Semeru Runtime Open Edition 11.0.22.0 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0 (build openj9-0.43.0, JRE 11 Linux amd64-64-Bit Compressed References 20240131_966 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 7876cac747 based on jdk-11.0.22+7)
```

```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Linux amd64-64-Bit Compressed References 20240116_670 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)
```

## Problem summary

We have defined a bytecode file where the minor version is set to -123, which we think is an incorrect value. openJ9-8 is able to report UnsupportedClassVersionError, while OpenJ9-11, 17 report nothing, is this because 11 and 17 are able to parse it correctly, or are they skipped some cases?

Steps to Reproduce
```
java-11/bin/java test
```
Expected Result
```
UnsupportedClassVersionError
```
Actual Result
```
nothing
```
## Sourcd Code
```
public class test extends ClassLoader {
    private static byte[] DATA;

    static {
        DATA = new byte[]{-54, -2, -70, -66, 0, -123, 0, 52, 0, 13, 10, 0, 3, 0, 10, 7, 0, 11, 7, 0, 12, 1, 0, 6, 60, 105, 110, 105, 116, 62, 1, 0, 3, 40, 41, 86, 1, 0, 4, 67, 111, 100, 101, 1, 0, 15, 76, 105, 110, 101, 78, 117, 109, 98, 101, 114, 84, 97, 98, 108, 101, 1, 0, 10, 83, 111, 117, 114, 99, 101, 70, 105, 108, 101, 1, 0, 18, 84, 101, 115, 116, 67, 97, 115, 101, 48, 48, 48, 48, 48, 46, 106, 97, 118, 97, 12, 0, 4, 0, 5, 1, 0, 13, 84, 101, 115, 116, 67, 97, 115, 101, 48, 48, 48, 48, 48, 1, 0, 16, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 79, 98, 106, 101, 99, 116, 0, 32, 0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 5, 0, 1, 0, 6, 0, 0, 0, 29, 0, 1, 0, 1, 0, 0, 0, 5, 42, -73, 0, 1, -79, 0, 0, 0, 1, 0, 7, 0, 0, 0, 6, 0, 1, 0, 0, 0, 1, 0, 1, 0, 8, 0, 0, 0, 2, 0, 9};
    }

    public test() {
    }
    public static void main(String[] var0) throws Exception {
        test t = new test();
        t.resolveClass(t.defineClass(DATA, 0, DATA.length));
    }
}
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@theresa-m Please take a look at this

**Comment by theresa-m** [comment]
First, a class's minor version is defined in the jvm spec as an unsigned type `u2 minor_version;` and will not be read in as a negative number. This class when consumed has the version 52.133.

The Java 8 exception is correctly thrown because the largest class version it can support is 52.0.

Starting in Java 12 the minor version .133 is accepted as a valid minor version:
> For a class file whose major_version is between 45 and 55 inclusive, the minor_version may be any value.

For Java 11 in the JVMS spec chapter 4.1 there are no restrictions given for the value of a minor verison. However starting in the Java 12 spec there is a note that historically JDK's have only accepted 0 as a valid minor version:
>  Later JDKs continued the practice of introducing support for a new major version (47, 48, etc) but supporting only a minor version of 0 under the new major version. 

Hotspot has this behavior throwing an UnsupportedClassVersionError. This behavior also existed in OpenJ9 [at one point](https://github.com/eclipse-openj9/openj9/blob/3ddd56b705757e978be121a87c932e3d37c95206/runtime/bcutil/cfreader.c#L2096-L2099) but was [refactored out](https://github.com/eclipse-openj9/openj9/pull/2680) I believe by mistake. I will open a change to fix this.

**Comment by theresa-m** [comment]
First, a class's minor version is defined in the jvm spec as an unsigned type `u2 minor_version;` and will not be read in as a negative number. This class when consumed has the version 52.133.

The Java 8 exception is correctly thrown because the largest class version it can support is 52.0.

The behavior for 17+ is also correct. Starting in Java 12 the minor version .133 is accepted as a valid minor version:
> For a class file whose major_version is between 45 and 55 inclusive, the minor_version may be any value.

For Java 11 in the JVMS spec chapter 4.1 there are no restrictions given for the value of a minor verison. However starting in the Java 12 spec there is a note that historically JDK's have only accepted 0 as a valid minor version of the latest major version but that doesn't apply in this case:
>  Later JDKs continued the practice of introducing support for a new major version (47, 48, etc) but supporting only a minor version of 0 under the new major version. 

The RI throws an UnsupportedClassVersionError for Java 11 since the minor version is not 0. Since its not part of the spec to throw an error I'm not sure if it makes sense to change OpenJ9's behavior. @TobiAjila ?

**Comment by tajila** [comment]
> The RI throws an UnsupportedClassVersionError for Java 11 since the minor version is not 0. Since its not part of the spec to throw an error I'm not sure if it makes sense to change OpenJ9's behavior. @TobiAjila ?

Sounds like there is not requirement on our part to do anything hear. However, if the change is simple and doesnt adversly impact J9 I woudl suggest making it for the sake of compatibility with the RI.

**Comment by theresa-m** [comment]
I tried this out with https://github.com/eclipse-openj9/openj9/pull/19340 but quickly ran into a failure building tests internally with third party packages that have non-zero minor versions. Given that this isn't a necessary change I think its best to leave the behavior as is.
