### ISSUE TITLE
Liberty starts slower with Semeru 17.0.9 than Semeru 11 

### ISSUE THREAD

**Issue by gjdeval** [eclipse-openj9/openj9#19152]
The magnitude of slowdown depends on the configuration and whether trace is enabled. Profiling shows extra time is spent in application threads, not garbage collection, but the affected application thread(s) are often executing routines in libj9gc29.so. The slowdown is only present when trace is enabled on startup. Linux perf reports for Semeru 11 and Semeru 17 are attached.

[perf-report-JDK11-15.2secs.txt](https://github.com/eclipse-openj9/openj9/files/14607772/perf-report-JDK11-15.2secs.txt)
[perf-report-JDK17.9-21.1secs.txt](https://github.com/eclipse-openj9/openj9/files/14607773/perf-report-JDK17.9-21.1secs.txt)

**Comment by jdmpapin** [comment]
Fixed in https://github.com/eclipse-openj9/openj9/pull/19187
0.44: https://github.com/eclipse-openj9/openj9/pull/19213
JDK next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/759
JDK22: https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/35
JDK21: https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/136
JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/333
