### ISSUE TITLE
jdk23 ReentrantLockTest::testAwaitUninterruptibly timed out waiting for thread to enter thread state WAITING

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19304]
jdk23 testing on amac
```
17:09:02  openjdk version "23-internal" 2024-09-17
17:09:02  OpenJDK Runtime Environment (build 23-internal-adhoc.****.BuildJDKnextaarch64macPersonal)
17:09:02  Eclipse OpenJ9 VM (build master-b2db2045aa4, JRE 23 Mac OS X aarch64-64-Bit 20240411_113 (JIT enabled, AOT enabled)
17:09:02  OpenJ9   - b2db2045aa4
17:09:02  OMR      - 0e07ad19c1f
17:09:02  JCL      - 7ac6a9b5b39 based on jdk-23+17)
```

Requires more triage to determine if this is jdk23 specific or an intermittent failure.

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/4
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#others
```
17:24:56  STARTED    ReentrantLockTest::testAwaitUninterruptibly_fair 'testAwaitUninterruptibly_fair'
17:24:56  junit.framework.AssertionFailedError: timed out waiting for thread to enter thread state WAITING
17:24:56  	at junit.framework.Assert.fail(Assert.java:57)
17:24:56  	at junit.framework.TestCase.fail(TestCase.java:223)
17:24:56  	at JSR166TestCase.assertThreadBlocks(JSR166TestCase.java:1253)
17:24:56  	at ReentrantLockTest.testAwaitUninterruptibly(ReentrantLockTest.java:954)
17:24:56  	at ReentrantLockTest.testAwaitUninterruptibly_fair(ReentrantLockTest.java:922)
17:24:56  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:24:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
17:24:56  	at junit.framework.TestCase.runTest(TestCase.java:177)
17:24:56  	at JSR166TestCase.runTest(JSR166TestCase.java:406)
17:24:56  	at junit.framework.TestCase.runBare(TestCase.java:142)
17:24:56  	at JSR166TestCase.runBare(JSR166TestCase.java:397)
17:24:56  	at junit.framework.TestResult$1.protect(TestResult.java:122)
17:24:56  	at junit.framework.TestResult.runProtected(TestResult.java:142)
17:24:56  	at junit.framework.TestResult.run(TestResult.java:125)
17:24:56  	at junit.framework.TestCase.run(TestCase.java:130)
17:24:56  	at junit.framework.TestSuite.runTest(TestSuite.java:241)
17:24:56  	at junit.framework.TestSuite.run(TestSuite.java:236)
17:24:56  	at junit.framework.TestSuite.runTest(TestSuite.java:241)
17:24:56  	at junit.framework.TestSuite.run(TestSuite.java:236)
17:24:56  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
17:24:56  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
17:24:56  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
17:24:56  	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
17:24:56  	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
17:24:56  	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
17:24:56  	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
17:24:56  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
17:24:56  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
17:24:56  	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
17:24:56  	at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:142)
17:24:56  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
17:24:56  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
17:24:56  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:24:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
17:24:56  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
17:24:56  	at java.base/java.lang.Thread.run(Thread.java:1587)
17:24:56  FAILED     ReentrantLockTest::testAwaitUninterruptibly_fair 'testAwaitUninterruptibly_fair'

17:24:56  [ JUnit Tests: found 4089, started 4068, succeeded 4067, failed 1, aborted 0, skipped 0]
```

**Comment by pshipton** [comment]
3x grinder https://openj9-jenkins.osuosl.org/job/Grinder/3470/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Nightly_testList_0/2
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#forkjoinpool-common-parallelism
```
21:03:36  STARTED    ClassSource [className = 'ReentrantLockTest', filePosition = null] 'testAwaitUninterruptibly'
21:03:36  junit.framework.AssertionFailedError: timed out waiting for thread to enter thread state WAITING
21:03:36  	at junit.framework.Assert.fail(Assert.java:57)
21:03:36  	at junit.framework.TestCase.fail(TestCase.java:223)
21:03:36  	at JSR166TestCase.assertThreadBlocks(JSR166TestCase.java:1253)
21:03:36  	at ReentrantLockTest.testAwaitUninterruptibly(ReentrantLockTest.java:954)
21:03:36  	at ReentrantLockTest.testAwaitUninterruptibly(ReentrantLockTest.java:921)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/3 - [ub18-x86-1](https://openj9-jenkins.osuosl.org/computer/ub18-x86-1)
jdk_util_0
java/util/concurrent/tck/JSR166TestCase.java#security-manager
```
03:44:50  STARTED    ReentrantLockTest::testAwaitUninterruptibly_fair 'testAwaitUninterruptibly_fair'
03:44:50  junit.framework.AssertionFailedError: timed out waiting for thread to enter thread state WAITING
03:44:50  	at junit.framework.Assert.fail(Assert.java:57)
03:44:50  	at junit.framework.TestCase.fail(TestCase.java:223)
03:44:50  	at JSR166TestCase.assertThreadBlocks(JSR166TestCase.java:1253)
03:44:50  	at ReentrantLockTest.testAwaitUninterruptibly(ReentrantLockTest.java:954)
03:44:50  	at ReentrantLockTest.testAwaitUninterruptibly_fair(ReentrantLockTest.java:922)
```

**Comment by pshipton** [comment]
@tajila fyi I've set this as a blocker for jdk23 and I'm excluding the test for now.

https://github.com/adoptium/aqa-tests/pull/5262

**Comment by tajila** [comment]
@babsingh Please take a look

**Comment by ThanHenderson** [comment]
I set up a version of the test locally, the failure rate is ~4 to 6 failures per 1000 runs, and I've only seen it on Java 23 and next.

The test spawns [two threads](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/232379e919a96a4c61df665ba2c976a51db14f78/test/jdk/java/util/concurrent/tck/ReentrantLockTest.java#L928-L947) (`t1` and `t2`) that both call  [this](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/232379e919a96a4c61df665ba2c976a51db14f78/src/java.base/share/classes/java/util/concurrent/locks/AbstractQueuedSynchronizer.java#L1650) `awaitUninterruptibly()`.

The javacore file's identify that `t2` is `waiting to be notified` about the `publicFlagsMutex` (which is stated to be `unowned`). The native thread's `vmstate` is `CW` (sleeping) and the `j9vmthread` state is `R` (runnable); I'd expect the [calls](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/232379e919a96a4c61df665ba2c976a51db14f78/src/java.base/share/classes/java/util/concurrent/ForkJoinPool.java#L4021) to `park`  to put the thread in a `P` state but this isn't the case.

Tried on RI too for JDK23 and there is no failure there. Still looking into our code.

**Comment by ThanHenderson** [comment]
There is a data race introduced [here](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/db0c0c0317584fd2287e42b1114b7bd451b14849).

Now that the volatile `interrupted` member is outside of a `synchronized(interruptLock)` block, the call to [Thread.interrupted()](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/76c3bac1f7bb391ad98ec8b732f5c4841de0836d/src/java.base/share/classes/java/util/concurrent/locks/AbstractQueuedSynchronizer.java#L1658) (which checks for and clears an interrupt), and [t2.interrupt()](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/76c3bac1f7bb391ad98ec8b732f5c4841de0836d/test/jdk/java/util/concurrent/tck/ReentrantLockTest.java#L950) (which sets `interrupted` to true) race for the value of `interrupted`. The failing case gets caught in[ this loop](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/76c3bac1f7bb391ad98ec8b732f5c4841de0836d/src/java.base/share/classes/java/util/concurrent/locks/AbstractQueuedSynchronizer.java#L514-L522) because, on the first iteration, during the `Thread.interrupted()` call, `interrupted` is false and thus doesn't execute the path through `clearInterruptEvent() -> interruptedImpl()` that clears the `J9THREAD_FLAG_INTERRUPTED`. This leads to a situation where `Thread::isInterrupted()` evaluates to false but the thread still has `J9THREAD_FLAG_INTERRUPTED` set. Then, in this call, `omrthread_park` is [short circuited](https://github.com/eclipse/omr/blob/de311dd2b79515a5c8472b292f527314ce4f4c21/thread/common/omrthread.c#L3285-L3286) because  `J9THREAD_FLAG_INTERRUPTED` is set and thus `J9THREAD_FLAG_PARKED` [never gets set](https://github.com/eclipse/omr/blob/de311dd2b79515a5c8472b292f527314ce4f4c21/thread/common/omrthread.c#L3290). The loop condition then gets stuck in the state where `status == 3` and `Thread.currentThread().isInterrupted() == false`.

The solution is just to include the `interrupted = true` in the synchronization block that was enclosed in `interrupt0` in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/803, that is, remove the `synchronized` block from within `interrupt0` and do this:
```
synchronized(interruptLock) {
    interrupted = true;
    interrupt0;
}
```
in `Thread::interrupt`. On my local testing, this passes on 20K runs for JDK next. This will also need to be backported to JDK 21, 22, and 23 extension repos.

**Comment by babsingh** [comment]
do all locations, where `Thread.interrupted` is written, need to be synchronized?

**Comment by ThanHenderson** [comment]
No. None do.

**Comment by ThanHenderson** [comment]
Fixed in:
JDKnext: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/812
JDK23: https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/11

**Comment by babsingh** [comment]
@ThanHenderson Reopening, the test needs to be enabled.

**Comment by ThanHenderson** [comment]
aqa-test PR to re-enable: https://github.com/adoptium/aqa-tests/pull/5431

**Comment by ThanHenderson** [comment]
The PR un-excluding the tests is now merged: https://github.com/adoptium/aqa-tests/pull/5431. Closing this as completed.
