### ISSUE TITLE
Loading classes from a jar file without ".jar" extension at classpath generates stale classes in shared class cache

### ISSUE THREAD

**Issue by imkabir** [eclipse-openj9/openj9#19378]
In a customer test we observed that if we specify a jar file without ".jar" extension in classpath, the code run generates stale classes for all the classes in the jar file in each subsequent runs - without any timestamp change to the jar file. Renaming the jar file adding the ".jar" extension stops the growth of the stale class. 

Adding _Trc_PRT_file_lastmod_Entry_ and _Trc_PRT_file_lastmod_Exit_ tracing, it was found that `stat ()` returns error in problematic case.

This is affecting short running frequently called JVMs as the class cache gets filled with stale classes. 

Attached one simple testcase. README.txt explains how to run it. I tested it on Linux.
```
openjdk version "21.0.2" 2024-01-16 LTS
IBM Semeru Runtime Open Edition 21.0.2.0 (build 21.0.2+13-LTS)
Eclipse OpenJ9 VM 21.0.2.0 (build openj9-0.43.0, JRE 21 Linux amd64-64-Bit Compressed References 20240116_94 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 78c4500a434 based on jdk-21.0.2+13)
```
Reproducible on Semeru 8 as well.

[mytest.zip](https://github.com/eclipse-openj9/openj9/files/15111075/mytest.zip)

**Comment by pshipton** [comment]
@tajila @hangshao0 fyi

**Comment by hangshao0** [comment]
@theresa-m Could you look at this. The code is [here](https://github.com/eclipse-openj9/openj9/blob/b8e94b159892235eab1f387f6ea78df8ded9055e/runtime/jcl/common/shared.c#L564-L582). 

Rather than relying on the file extension, we should add check on the path using `j9file_attr()` to return to correct type,  i.e.  `CPE_TYPE_DIRECTORY` for a directory, `CPE_TYPE_JAR` for a jar file.
