### ISSUE TITLE
Abstract Method Error in OpenJ9 OpenJDK 8 on Specific Test Case

### ISSUE THREAD

**Issue by RuifengFu** [eclipse-openj9/openj9#19376]
Java -version output
--------------------

openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20240131_874 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)

Summary of problem
------------------
A test case that involves method overriding with a different signature in a subclass is failing on OpenJ9 OpenJDK 8, while it passes on OpenJ9 OpenJDK 11, HotSpot JDK 11, and HotSpot JDK 8. The test case consists of an interface with an abstract method, a class implementing the interface without implementing the method, and a subclass of that class with a private instance method of the same name but a different signature.

On OpenJ9 OpenJDK 8, the test case throws an IllegalAccessError instead of the expected AbstractMethodError. However, on other JDK versions and implementations, the test case behaves as expected and throws an AbstractMethodError.

The expected behavior is for the test case to consistently throw an AbstractMethodError across all JDK versions and implementations, including OpenJ9 OpenJDK 8. The inconsistent behavior observed on OpenJ9 OpenJDK 8 is considered a bug, as it deviates from the expected and consistent behavior observed on other JDK versions and implementations.

Diagnostic files
----------------
Expect result:
```
Ran 1566 cases
All test cases succeeded
```
Real result:
```
Ran 1566 cases
Errors occurred in test:
Failed:                 
invoke:    INVOKEVIRTUAL
methodref: C1
objectref: C2
callsite: C1
result: Result=Exception{exc=class java.lang.AbstractMethodError}
classes:

interface Same.I0 { public  abstract Integer m(); }

class Same.C1 implements I0 {  }

class Same.C2 extends C1 { private instance Integer m(); }


Expected Result=Exception{exc=class java.lang.AbstractMethodError} got java.lang.IllegalAccessError: P0/C2.m()Ljava/lang/Integer;
Classes written to error_0
Failed:
invoke:    INVOKEVIRTUAL
methodref: C1
objectref: C3
callsite: C1
result: Result=Exception{exc=class java.lang.AbstractMethodError}
classes:

interface Same.I0 { public  abstract Integer m(); }

class Same.C1 implements I0 {  }

class Same.C2 extends C1 { private instance Integer m(); }

class Same.C3 extends C2 {  }


Expected Result=Exception{exc=class java.lang.AbstractMethodError} got java.lang.IllegalAccessError: P0/C2.m()Ljava/lang/Integer;
Classes written to error_1


...
```

[AbstractMethodErrorTest](https://github.com/eclipse-openj9/openj9/files/15108016/test.zip)

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@ThanHenderson Please take a look at this

**Comment by RuifengFu** [comment]
> @RuifengFu Do you have the command used to compile and run the tests?

`
javac test/*.java
java  test.AbstractMethodErrorTest
`

**Comment by ThanHenderson** [comment]
If I am understanding the [specification section](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.4) correctly, throwing an `IllegalAccessError`, seems to be the correct behaviour for JDK8.

Specifically,

> If method lookup succeeds and the referenced method is not accessible ([§5.4.4](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.4)) to D, interface method resolution throws an `IllegalAccessError`.

where `D` is the class where the interface method is being invoked from.

For the first test case that is failing (`error_0` above), the corresponding Java code would be something similar to the following.
```
interface I {
  abstract int m();
}

class C1 implements I {
  public static void test() {
    C2 c2 = new C2();
    c2.m();
  }
}

class C2 extends C1 {
  private int m() {
    return 10;
  }
}

public class Test2 {
  public static void main(String[] args) { 
    C1.test();
  }
}
```

First thing to note is that code like this is invalid and rejected by `javac` (i.e. `C1` doesn't implement `m` and `C1` cannot access `C2::m`). So the situation as such wouldn't arise in valid Java code. However, these test cases were generated with the ASM API and executed directly.

In the case above, the error is being thrown when `C1` tries to invoke `c2.m()`. `C2::m` is found during resolution, then a check is performed to determine the accessibility from the invoking class `C1`. Since `C1` doesn't have access to because `C2::m` is `private`, the `IllegalAccessError` is thrown, in agreement with the specification excerpt above.

@tajila Do you agree with this reasoning? If so, do you think we should leave things as they are or match the RI's behaviour?

**Comment by tajila** [comment]
> If I am understanding the [specification section](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.4) correctly, throwing an IllegalAccessError, seems to be the correct behaviour for JDK8.

Can you verify that `c2.m();` is an invokeinterface call to I::m() in the bytecodes? If so,  the method being resolved is `I::m()`

Assuming it is...

Based on https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.6 and https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.5 our JDK11+ implementation sounds correct. `I::m()` is resolved but no method can be selected since, `class C1` doesnt implement it and private methods (`C2::m()`) cannot override. So the result must be AME.

It would appear that https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokeinterface permits us to select the private method in JDK8.

```
Let C be the class of objectref. The actual method to be invoked is selected by the following lookup procedure:

    If C contains a declaration for an instance method with the same name and descriptor as the resolved method, then it is the method to be invoked.
```

But when we execute the selected method IAE is thrown 

```
Otherwise, if step 1 or step 2 of the lookup procedure selects a method that is not public, invokeinterface throws an IllegalAccessError. 
```
So I think our behaviour is in fact correct in JDK8. The RI behaves as though no method can be selected, which I would argue is wrong according to the Java 8 spec. 

Perhaps the Java8 spec is in error, given that the wording is changed in Java11. In either case, I dont think we need to do anything for this.

**Comment by ThanHenderson** [comment]
@tajila it is actually an `invokevirtual` call (https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokevirtual).

```
  public static java.lang.Integer test();
    Code:
       0: invokestatic  #18                 // Method P0/Helper.getC2:()LP0/C2;
       3: astore_1
       4: aload_1
       5: invokevirtual #21                 // Method m:()Ljava/lang/Integer;      <-------------------
       8: areturn
```
`invokevirutal` for Java 8 throws an IAE under the following condition:
> if the resolved method is a protected method of a superclass of the current class, declared in a different run-time package, and the class of objectref is not the current class or a subclass of the current class, then invokevirtual throws an IllegalAccessError.

And an AME under:
> If step 1 or step 2 of the lookup procedure selects an abstract method, invokevirtual throws an AbstractMethodError.

Where step 1 and step 2 are:
> Let C be the class of objectref. The actual method to be invoked is selected by the following lookup procedure:
>   1. If C contains a declaration for an instance method m that overrides ([§5.4.5](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.5)) the resolved method, then m is the method to be invoked.
>   2. Otherwise, if C has a superclass, a search for a declaration of an instance method that overrides the resolved method is performed, starting with the direct superclass of C and continuing with the direct superclass of that class, and so forth, until an overriding method is found or no further superclasses exist. If an overriding method is found, it is the method to be invoked.

Which is a bit more difficult to parse in this case. The descriptions don't really mention anything about accessibility.

Java 11 doesn't mention anything about IAE for `invokevirtual` (https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.invokevirtual)

**Comment by ThanHenderson** [comment]
I am still leaning toward:

> If I am understanding the [specification section](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.4) correctly, throwing an IllegalAccessError, seems to be the correct behaviour for JDK8.

being the correct answer here because resolution would throw an IAE in the context and the `invokevirtual` spec states:

> During resolution of the symbolic reference to the method, any of the exceptions pertaining to method resolution ([§5.4.3.3](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3)) can be thrown.

**Comment by tajila** [comment]
>     5: invokevirtual #21                 // Method m:()Ljava/lang/Integer; 

Which class does the method belong to?

**Comment by ThanHenderson** [comment]
C2

**Comment by tajila** [comment]
> being the correct answer here because resolution would throw an IAE in the context and the invokevirtual spec states:
>>  During resolution of the symbolic reference to the method, any of the exceptions pertaining to method resolution ([§5.4.3.3](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.3)) can be thrown.

Yes thats my undersanding of it as well. 

Although now, I'm struggling to explain the JDK11 behaviour. It would imply that the method lookup is different in JDK11.

**Comment by ThanHenderson** [comment]
> I'm struggling to explain the JDK11 behaviour. It would imply that the method lookup is different in JDK11.

Regardless, I think we can still close this issue for the 0.46 release, and look into the JDK11 version separately if we need to.
