### ISSUE TITLE
OpenJDK VarHandleTest expected object to not be null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19693]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_1/130/
jdk_lang_VarHandleTest_j9_0
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java.VarHandleTestByteArrayAsChar
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsDouble.java.VarHandleTestByteArrayAsDouble
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java.VarHandleTestByteArrayAsFloat
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java.VarHandleTestByteArrayAsInt
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsLong.java.VarHandleTestByteArrayAsLong
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsShort.java.VarHandleTestByteArrayAsShort

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_2/130/
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java.VarHandleTestByteArrayAsChar
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsDouble.java.VarHandleTestByteArrayAsDouble
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java.VarHandleTestByteArrayAsFloat
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java.VarHandleTestByteArrayAsInt
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsLong.java.VarHandleTestByteArrayAsLong
    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsShort.java.VarHandleTestByteArrayAsShort

```
18:08:15  test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, BIG_ENDIAN, READ_WRITE] -> java.nio.HeapByteBufferR[pos=0 lim=32 cap=32] [ALIGNED, BIG_ENDIAN, READ_ONLY] unsupported", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@46d83fd3): failure
18:08:15  java.lang.AssertionError: No throwable thrown. Expected class java.nio.ReadOnlyBufferException expected object to not be null
18:08:15  	at org.testng.Assert.fail(Assert.java:99)
18:08:15  	at org.testng.Assert.assertNotNull(Assert.java:942)
18:08:15  	at VarHandleBaseTest.checkWithThrowable(VarHandleBaseTest.java:147)
18:08:15  	at VarHandleBaseTest.checkROBE(VarHandleBaseTest.java:65)
18:08:15  	at VarHandleTestByteArrayAsChar.testArrayUnsupported(VarHandleTestByteArrayAsChar.java:421)
18:08:15  	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$14(VarHandleTestByteArrayAsChar.java:205)
18:08:15  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:420)
18:08:15  	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:229)
```

Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/58b586d83e7...e4f8c0ab849
https://github.com/eclipse-openj9/openj9-omr/compare/873509033...c8ff027da76

Likely caused by https://github.com/eclipse-openj9/openj9/pull/19566
@0xdaryl @jdmpapin

**Comment by jdmpapin** [comment]
`VarHandleTestByteArrayAsInt` failed 10/10 in a grinder. I spun up a VM to run it myself, but it doesn't seem to reproduce at all there. I'm waiting for access to rh8-390-2, where my grinder ran, so that I can hopefully reproduce the issue manually there and narrow down the compilation with a limit file

**Comment by jdmpapin** [comment]
The bug appeared not to reproduce manually on rh8-390-2 either, despite another grinder that failed 5/5 on the same machine

It turns out that I had set `CUSTOM_TARGET` instead of `JDK_CUSTOM_TARGET` when running the test, which resulted in aqa-tests/TKG running a different test and reporting a pass with output that looked like it was using my `CUSTOM_TARGET` value...

Running the correct test using `JDK_CUSTOM_TARGET`, the failure reproduces on rh8-390-2, but it also reproduces on my VM, so now I'm proceeding there after all
