### ISSUE TITLE
J9 verification permits non-interfaces on operand stack of invokeinterface 

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#19756]
With the following example:

```
Interface val = new Concrete[elements];
val.ifaceMethod(); //throws IncompatibleClassChangeError on J9 whereas RI throws a verification failure much earlier
```

Test files:
[TestFiles.zip](https://github.com/user-attachments/files/15974115/TestFiles.zip)

Run with:
`java TestInterface` 

We need to align the behaviour with RI for the following reasons
1) It forces the JIT to be conservative and treat every interface type as a potential array
2) Better aligns J9 behaviour with the RI

**Comment by theresa-m** [comment]
There's not currently a way to distinguish the array of a reference/object from an object. See the 5 bits that are reserved for types https://github.com/eclipse-openj9/openj9/blob/master/runtime/oti/bytecodewalk.h#L100-L104
I think BCV_TAG_BASE_ARRAY_OR_NULL can be redefined to mean a reference or a base array so that:
- 0x10 tag means a reference array
- 0x11 means a base array
Does that make sense @TobiAjila ?

**Comment by tajila** [comment]
> There's not currently a way to distinguish the array of a reference/object from an object.

I thought it was `classIndex | (arity << BCV_ARITY_SHIFT)` with the implied `BCV_JAVA_LANG_OBJECT_INDEX` bit set ?

**Comment by theresa-m** [comment]
Oh right that makes sense. I'll try that, thanks.
