### ISSUE TITLE
JEP 498: Warn upon Use of Memory-Access Methods in sun.misc.Unsafe

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#20632]
See https://openjdk.org/jeps/498

**Comment by theresa-m** [comment]
I don't think there is any vm work to do here. I will run the OpenJ9 functional tests with `--sun-misc-unsafe-memory-access=warn` to see if any tests will fail once it becomes the default setting.

**Comment by pshipton** [comment]
I would be good to run openjdk testing as well. 

What happens if we run with `--sun-misc-unsafe-memory-access=deny`? If there is usage from OpenJ9 class library code that is going to generate warnings, I think it needs to be removed so user's don't get these warnings.

**Comment by theresa-m** [comment]
I'll try with openjdk tests and `--sun-misc-unsafe-memory-access=deny` as well.

OpenJ9 does not generate any warning for this, it is done in https://github.com/openjdk/jdk/blob/master/src/jdk.unsupported/share/classes/sun/misc/Unsafe.java#L1860

**Comment by pshipton** [comment]
The point is that OpenJ9 implements JCL code that uses Unsafe. If this code ends up generating a warning when run in a user application, this needs to be fixed.

**Comment by hzongaro** [comment]
> The point is that OpenJ9 implements JCL code that uses Unsafe. If this code ends up generating a warning when run in a user application, this needs to be fixed.

Does the OpenJ9 JCL code after version 8 use `sun.misc.Unsafe` or only `jdk.internal.misc.Unsafe`?  Will warnings be reported for uses of either or only the former?

**Comment by theresa-m** [comment]
I tried sanity and extended tests with `--sun-misc-unsafe-memory-access=deny`
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Simple/39/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Simple/39/

The 3 test failures are all due to direct uses of the sun.misc.Unsafe library.
- Test_UnsafeFence.testIntFence
- Test_UnsafeFence.testLongFence
- Cmvc199515.testCmvc199515

I'll try OpenJDK tests next.

**Comment by pshipton** [comment]
I can't think of anything else. Thanks for double checking.
