### ISSUE TITLE
Investigate best AArch64 instructions for memory fences

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#6332]
The AArch64 JIT implementation of the fence opcodes (`TR::loadFence`, `TR::storeFence`, `TR::fullFence`) uses a conservatively correct `DSB` instruction.

The task here is to understand the AArch64 memory model and choose the best memory barrier instructions that meet the semantics of the Java memory model.

**Comment by 0xdaryl** [comment]
@Akira1Saitoh : fyi

**Comment by Akira1Saitoh** [comment]
According to Arm Architecture Reference Manual,
> The DMB instruction is a memory barrier instruction that ensures the relative order of memory accesses before the
barrier with memory accesses after the barrier. The DMB instruction does not ensure the completion of any of the
memory accesses for which it ensures relative order.

> A DSB is a memory barrier that ensures that memory accesses that occur before the DSB have completed before
the completion of the DSB instruction. In doing this, it acts as a stronger barrier than a DMB and all ordering that
is created by a DMB with specific options is also generated by a DSB with the same options.

> A DSB executed by a PE, PEe, completes when all of the following apply:
• All explicit memory accesses of the required access types appearing in program order before the DSB are
complete for the set of observers in the required shareability domain.
• If the required access types of the DSB is reads and writes, then all cache maintenance instructions, all TLB
maintenance instructions, and all PSB CYNC instructions issued by PEe before the DSB are complete for the
required shareability domain.

Also, a blog article in ARM website says:
 https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/memory-access-ordering-part-3---memory-access-ordering-in-the-arm-architecture
> The Data Synchronization Barrier enforces the same ordering as the Data Memory Barrier, but it also blocks execution of any further instructions until synchronization is complete. It also waits until all cache and branch predictor maintenance operations have completed for the specified shareability domain. If the access type is load and store then it also waits for any TLB maintenance operations to complete.
In the Linux kernel, the DSB instruction is used for the *mb() macros.

*mb() macros are described as 'Mandatory barriers' in the page 2 of the same article:

>Mandatory barriers
Mandatory barriers are used to enforce memory consistency on a full system level. The most common example of this is when communicating with external memory mapped peripherals. All mandatory barriers are guaranteed to expand to at least a compiler barrier, regardless of target architecture.   

So, the DMB instruction ensures that relative order of memory accesses before it and memory accesses after it.
In addition to this, the DSB instruction ensures the completion of memory access before the DSB instruction and its main usage seems to be to make sure access to the memory mapped peripherals completes before instructions after the DSB instruction are executed.

The fence operations described in [JEP 193](https://openjdk.java.net/jeps/193) does not
require completion of memory access before completion of fence methods.

>/**
    * Ensures that loads and stores before the fence will not be
    * reordered with loads and stores after the fence.
    *
    * @ apiNote Ignoring the many semantic differences from C and
    * C++, this method has memory ordering effects compatible with
    * atomic_thread_fence(memory_order_seq_cst)
    */

Those fences ensures that memory accesses before the fence are not reordered with memory accesses after the fence.
Thus, we can use the DMB instruction instead of the DSB instruction.

**Comment by Akira1Saitoh** [comment]
For shareabiilty domain parameter of the DMB instruction, the correct one seems to be inner shareable domain.
Arm Architecture Reference Manual says:
>This architecture assumes that all PEs that use the same operating system or hypervisor are in the same Inner
Shareable shareability domain.

Inner shareable domain seems to be widely used for barriers between processors.
Taking C++ as an example,`std::atomic_thread_fence` generates `DMB ishld` for `std::memory_order_acquire`, `DMB ish` for `memory_order_release`, `memory_order_acq_rel`, and `memory_order_seq_cst`.
You can find mappings between C++ atomic operations to processor instructions here:
https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html

**Comment by Akira1Saitoh** [comment]
From Arm Architecture Reference Manual,

> A read or a write RW1 is Barrier-ordered-before a read or a write RW2 from the
> same Observer if and only if RW1 appears in program order before RW2 and any of the following
> cases apply:
> ...
> - RW1 appears in program order before a DMB FULL that appears in program order before RW2.
> ...
> - RW1 is a read R1 and either:
>   - R1 appears in program order before a DMB LD that appears in program order before RW2.
> ...
> - RW2 is a write W2 and either:
>   - RW1 is a write W1 appearing in program order before a DMB ST that appears in program order before W2.
> 

Thus, the mappings of a fence op to a barrier instruction should be:

|  VarHandle fence op    |    barrier instruction     |
|--------------|--------------|
|   acquire     |      dmb ishld     |
|   loadLoad     |      dmb ishld     |
|   storeStore     |      dmb ishst     |
|   release     |      dmb ish     |
|   full     |      dmb ish     |

Currently, the mappings of a fence operation to an opcode are as follows:
`acquireFence` -> `TR::loadFence`
https://github.com/eclipse/openj9/blob/ee83667b9f465f989a13400f5f0139821cf7fb63/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L880-L883
`fullFence` -> `TR::fullFence`
https://github.com/eclipse/openj9/blob/ee83667b9f465f989a13400f5f0139821cf7fb63/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L872-L874
`releaseFence` -> `TR::storeFence`
https://github.com/eclipse/openj9/blob/ee83667b9f465f989a13400f5f0139821cf7fb63/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L889-L892
`loadLoadFence` -> `TR::loadFence`
https://github.com/eclipse/openj9/blob/ee83667b9f465f989a13400f5f0139821cf7fb63/jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java#L5515-L5517
`storeStoreFence` -> `TR::storeFence`
https://github.com/eclipse/openj9/blob/ee83667b9f465f989a13400f5f0139821cf7fb63/jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java#L5523-L5525

So, for each fence IL opcode, we should generate following instructions:
|  fence IL opcode    |    barrier instruction     |
|--------------|--------------|
|   loadFence     |      dmb ishld     |
|   storeFence     |      dmb ish     |
|   fullFence     |      dmb ish     |

Unfortunately, we need to use `dmb ish` for `storeStoreFence` because `storeStoreFence` is mapped to `TR::storeFence`.

**Comment by Akira1Saitoh** [comment]
ARMv8 has load-acquire and store-release instructions which can be used instead of memory barrier instructions.
From `Definition of the Armv8 memory model` in ARM Architecture Reference Manual,

> A read or a write RW1 is Barrier-ordered-before a read or a write RW2 from the
> same Observer if and only if RW1 appears in program order before RW2 and any of the following
> cases apply:
> …
> • RW1 appears in program order before an atomic instruction with both Acquire and Release
> semantics that appears in program order before RW2.
> • RW1 is a write W1 generated by an instruction with Release semantics and RW2 is a read R2,
> except a Tag-Check-read, generated by an instruction with Acquire semantics.
> …
> • RW1 is a read R1, except a Tag-Check-read, and is generated by an instruction with Acquire
> or AcquirePC semantics.
> …
> • RW2 is a write W2 and is generated by an instruction with Release semantics.
> 

In short,
- No loads/stores after a load-acquire instruction can be reordered before it,
- No loads/stores before a store-release instruction can be reordered after it.
- A load-acquire instruction after a store-release instruction cannot be reordered before it.

**Comment by 0xdaryl** [comment]
Complete.
